import async_js from "./python/async_js.py"
import completer from "./python/completer.py"
import crappy_multitasking from "./python/crappy_multitasking.py"
import execution from "./python/execution.py"
import executor from "./python/executor.py"
import handler_decorator from "./python/handler_decorator.py"
import send_message from "./python/send_message.py"
import sseq_display from "./python/sseq_display.py"
import traceback from "./python/traceback.py"
import webloop from "./python/webloop.py"
import write_stream from "./python/write_stream.py"
import __init__ from "./python/__init__.py"
export const files_to_install = {async_js,completer,crappy_multitasking,execution,executor,handler_decorator,send_message,sseq_display,traceback,webloop,write_stream,__init__}