import initialize_pyodide_0 from "./python/initialize_pyodide.py";
import namespace_1 from "./python/namespace.py";
import sseq_display_2 from "./python/sseq_display.py";
import working_directory_3 from "./python/working_directory.py";
import async_js_4 from "./python/js_wrappers/async_js.py";
import filesystem_5 from "./python/js_wrappers/filesystem.py";
import messages_6 from "./python/js_wrappers/messages.py";
import __init___7 from "./python/js_wrappers/__init__.py";
import completer_8 from "./python/repl/completer.py";
import execution_9 from "./python/repl/execution.py";
import executor_10 from "./python/repl/executor.py";
import handler_decorator_11 from "./python/repl/handler_decorator.py";
import traceback_12 from "./python/repl/traceback.py";
import write_stream_13 from "./python/repl/write_stream.py";
import __init___14 from "./python/repl/__init__.py";
export const directories_to_install = ['js_wrappers', 'repl']; 
export const files_to_install = {'initialize_pyodide.py' : initialize_pyodide_0, 'namespace.py' : namespace_1, 'sseq_display.py' : sseq_display_2, 'working_directory.py' : working_directory_3, 'js_wrappers/async_js.py' : async_js_4, 'js_wrappers/filesystem.py' : filesystem_5, 'js_wrappers/messages.py' : messages_6, 'js_wrappers/__init__.py' : __init___7, 'repl/completer.py' : completer_8, 'repl/execution.py' : execution_9, 'repl/executor.py' : executor_10, 'repl/handler_decorator.py' : handler_decorator_11, 'repl/traceback.py' : traceback_12, 'repl/write_stream.py' : write_stream_13, 'repl/__init__.py' : __init___14};