import namespace_0 from "./python/namespace.py";
import sseq_display_1 from "./python/sseq_display.py";
import async_js_2 from "./python/js_wrappers/async_js.py";
import crappy_multitasking_3 from "./python/js_wrappers/crappy_multitasking.py";
import filesystem_4 from "./python/js_wrappers/filesystem.py";
import messages_5 from "./python/js_wrappers/messages.py";
import __init___6 from "./python/js_wrappers/__init__.py";
import completer_7 from "./python/repl/completer.py";
import execution_8 from "./python/repl/execution.py";
import executor_9 from "./python/repl/executor.py";
import handler_decorator_10 from "./python/repl/handler_decorator.py";
import traceback_11 from "./python/repl/traceback.py";
import write_stream_12 from "./python/repl/write_stream.py";
import __init___13 from "./python/repl/__init__.py";
export const directories_to_install = ['js_wrappers', 'repl']; 
export const files_to_install = {'namespace.py' : namespace_0, 'sseq_display.py' : sseq_display_1, 'js_wrappers/async_js.py' : async_js_2, 'js_wrappers/crappy_multitasking.py' : crappy_multitasking_3, 'js_wrappers/filesystem.py' : filesystem_4, 'js_wrappers/messages.py' : messages_5, 'js_wrappers/__init__.py' : __init___6, 'repl/completer.py' : completer_7, 'repl/execution.py' : execution_8, 'repl/executor.py' : executor_9, 'repl/handler_decorator.py' : handler_decorator_10, 'repl/traceback.py' : traceback_11, 'repl/write_stream.py' : write_stream_12, 'repl/__init__.py' : __init___13};