[package]
name = "saveload"
version = "0.1.0"
authors = ["Dexter Chua <dalcde@yahoo.com.hk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.2.0"
parking_lot = "0.11.1"
