//! Compile the CUDA C++ kernel to PTX via nvcc.
//!
//! The emitted `matmul_b1.ptx` is picked up by `src/lib.rs` via
//! `include_bytes!(concat!(env!("OUT_DIR"), "/matmul_b1.ptx"))`.

use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{Context, bail};

const KERNEL_SRC: &str = "cuda_kernels/matmul_b1.cu";
const PARAMS_HEADER: &str = "cuda_kernels/params.h";
const PTX_NAME: &str = "matmul_b1.ptx";
const PARAMS_NAME: &str = "params.rs";
const ARCH: &str = "sm_90a";

/// Mirror the tuning knobs in `params.h` as Rust constants.
///
/// `params.h` is the header the kernel itself includes, so the host code cannot disagree with the
/// kernel about a tile size.
///
/// Reads `#define <NAME> <integer>` lines; anything else in the header (function-like macros, the
/// verification block, comments) is skipped. That makes this a deliberately naive reader of a
/// language whose preprocessor it cannot hope to evaluate, which is safe only because every value
/// it returns is checked against the real thing: the caller hands them back to nvcc, and `params.h`
/// static_asserts each one. See the `FP_CUDA_VERIFY` block there.
///
/// Returns the parsed knobs so they can be re-exported for that check.
fn emit_params(out_dir: &Path) -> Vec<(String, usize)> {
    let header = fs::read_to_string(PARAMS_HEADER)
        .unwrap_or_else(|e| panic!("failed to read {PARAMS_HEADER}: {e}"));

    let mut knobs = Vec::new();
    for line in header.lines() {
        let Some(rest) = line.strip_prefix("#define ") else {
            continue;
        };
        let mut it = rest.split_whitespace();
        let (Some(name), Some(value)) = (it.next(), it.next()) else {
            continue;
        };
        // Function-like macros (`NAME(args)`) are not knobs.
        if name.contains('(') {
            continue;
        }
        let Ok(value) = value.parse::<usize>() else {
            continue;
        };
        knobs.push((name.to_string(), value));
    }

    assert!(
        !knobs.is_empty(),
        "no `#define <NAME> <integer>` knobs found in {PARAMS_HEADER}; the header moved or its \
         format changed"
    );

    let mut rust = String::from("// Generated by build.rs from cuda_kernels/params.h.\n");
    for (name, value) in &knobs {
        rust.push_str(&format!("pub const {name}: usize = {value};\n"));
    }
    fs::write(out_dir.join(PARAMS_NAME), rust).expect("failed to write params.rs to OUT_DIR");

    knobs
}

fn main() -> anyhow::Result<()> {
    println!("cargo:rerun-if-changed={KERNEL_SRC}");
    println!("cargo:rerun-if-changed={PARAMS_HEADER}");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=NVCC");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR not set by cargo"));
    let ptx_out = out_dir.join(PTX_NAME);

    let knobs = emit_params(&out_dir);

    let nvcc = env::var("NVCC").unwrap_or_else(|_| "nvcc".to_string());

    let status = Command::new(&nvcc)
        .args([
            "-ptx",
            "-O3",
            "-std=c++17",
            "--use_fast_math",
            &format!("-arch={ARCH}"),
        ])
        // Hand every parsed value back to the compiler, which checks it against the macro it was
        // read from; see the `FP_CUDA_VERIFY` block in params.h.
        .arg("-DFP_CUDA_VERIFY")
        .args(
            knobs
                .iter()
                .map(|(name, value)| format!("-DFP_CUDA_VERIFY_{name}={value}")),
        )
        .args([KERNEL_SRC, "-o"])
        .arg(&ptx_out)
        .status()
        .with_context(|| {
            format!("failed to run nvcc ('{nvcc}'). Set the NVCC env var to a working nvcc.")
        })?;

    // A non-zero exit is `Ok` as far as `status()` is concerned, so it has to be turned into a
    // failure explicitly or the build script would succeed with no PTX written.
    if !status.success() {
        bail!(
            "nvcc failed to compile {KERNEL_SRC} ({status}). Check that your CUDA Toolkit \
             supports {ARCH} (Hopper)."
        );
    }

    Ok(())
}
