A = AdemAlgebra(2, unstable=True)
A.compute_basis(80)
M = FDModule(A, "M", 0)
M.add_generator(3, "x0")
M.freeze()
r = ext.resolution.Resolver("S3", module=M)
S3 = ResolverChannel(r, REPL)
S3.resolver.resolve(50)
