use fp::prime::iter::BitflagIterator;
use serde::{Deserialize, Serialize};

use super::PPartEntry;

fn q_part_default() -> u32 {
    !0
}

#[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MilnorProfile {
    /// If `true`, unspecified p_part entries will be 0. Otherwise they will be infinity.
    pub truncated: bool,
    /// A bitmask indicating which of the Q_k we want to include (1 = include). Defaults to `!0`.
    /// This is only relevant at odd primes.
    #[serde(default = "q_part_default")]
    pub q_part: u32,
    /// The profile function for the Q part.
    ///
    /// We need to allow Infinity here, so we don't bit-pack.
    #[serde(default)]
    pub p_part: Vec<PPartEntry>,
}

impl MilnorProfile {
    pub fn is_trivial(&self) -> bool {
        !self.truncated && self.q_part == !0 && self.p_part.is_empty()
    }

    pub fn get_p_part(&self, i: usize) -> PPartEntry {
        self.p_part
            .get(i)
            .copied()
            .unwrap_or(if self.truncated { 0 } else { PPartEntry::MAX })
    }

    /// Checks whether the profile function is valid
    pub fn is_valid(&self) -> bool {
        for (i, &hi) in self.p_part.iter().enumerate() {
            for (j, &hj) in self.p_part.iter().enumerate().skip(i + 1) {
                if hi > (j - i) as PPartEntry + hj && self.p_part[j - i - 1] > hj {
                    return false;
                }
            }
        }
        if self.truncated {
            let len = self.p_part.len();
            for (i, &hi) in self.p_part.iter().enumerate() {
                if hi > (len - i) as PPartEntry {
                    return false;
                }
            }
        }
        if self.q_part != !0 {
            for i in BitflagIterator::set_bit_iterator(!self.q_part as u64) {
                for j in 0..i {
                    if (self.q_part >> j) & 1 == 1 && self.get_p_part(i - j - 1) > j as PPartEntry {
                        return false;
                    }
                }
            }
        }
        true
    }

    /// Whether the profile is that of A(n). This is relevant since A(n) is generated by P(p^n) and
    /// β but a general subalgebra is not.
    pub fn is_an(&self, generic: bool) -> bool {
        if *self == Self::default() {
            return true;
        }
        if !self.truncated {
            return false;
        }
        if self.p_part.len() != self.p_part[0] as usize {
            return false;
        }
        if generic && self.q_part != (1 << (self.p_part.len() + 1)) - 1 {
            return false;
        }
        true
    }
}

impl Default for MilnorProfile {
    fn default() -> Self {
        Self {
            truncated: false,
            q_part: !0,
            p_part: Vec::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_valid_profile() {
        assert!(
            (MilnorProfile {
                p_part: vec![3, 2, 1],
                q_part: !0,
                truncated: true
            })
            .is_valid()
        );

        assert!(
            !(MilnorProfile {
                p_part: vec![3, 2],
                q_part: !0,
                truncated: true
            })
            .is_valid()
        );

        assert!(
            (MilnorProfile {
                p_part: vec![3, 2, 1],
                q_part: 0b1111,
                truncated: true
            })
            .is_valid()
        );

        assert!(
            (MilnorProfile {
                p_part: vec![2, 4, 2],
                q_part: 0,
                truncated: false
            })
            .is_valid()
        );

        assert!(
            !(MilnorProfile {
                p_part: vec![3, 2, 1],
                q_part: 0b111,
                truncated: true
            })
            .is_valid()
        );
    }
}
