[build-system]
requires = ["maturin>=1.8"]
build-backend = "maturin"

[project]
name = "sseq_ext"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "ext"
python-source = "python"

[dependency-groups]
dev = [
    "maturin>=1.8",
    "pytest",
]
