chart = SpectralSequenceChart("C2")
chart.set_initial_x_range(0, 40)
chart.set_initial_y_range(0, 20)
chart.set_x_range(0, 80)
chart.set_y_range(0, 40)

A = AdemAlgebra(2)
A.compute_basis(20)
M = FDModule(A, "M")
M.add_generator(0, "x0")
M.add_generator(1, "x1")
M.parse_action("Sq1 x0 = x1", None)
M.freeze()
res_c2 = Resolution("C(2)", chart=chart, module=M)