use std::cell::Cell;

use fp::{
    prime::{Binomial, Prime, ValidPrime, factor_pk, iter::BitflagIterator},
    vector::{FpSlice, FpSliceMut, FpVector},
};
use itertools::Itertools;
use once::OnceVec;
use rustc_hash::FxHashMap as HashMap;
use serde::{Deserialize, Serialize};

use crate::algebra::{Algebra, Bialgebra, GeneratedAlgebra, UnstableAlgebra, combinatorics};

fn q_part_default() -> u32 {
    !0
}

#[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MilnorProfile {
    /// If `true`, unspecified p_part entries will be 0. Otherwise they will be infinity.
    pub truncated: bool,
    /// A bitmask indicating which of the Q_k we want to include (1 = include). Defaults to `!0`.
    /// This is only relevant at odd primes.
    #[serde(default = "q_part_default")]
    pub q_part: u32,
    /// The profile function for the Q part.
    ///
    /// Unlike the exponent sequence of a basis element (see [`PPart`]), these are *exponents* of
    /// the profile function and use [`PPartEntry::MAX`] to mean infinity, so they stay unpacked.
    #[serde(default)]
    pub p_part: Vec<PPartEntry>,
}

impl MilnorProfile {
    pub fn is_trivial(&self) -> bool {
        !self.truncated && self.q_part == !0 && self.p_part.is_empty()
    }

    pub fn get_p_part(&self, i: usize) -> PPartEntry {
        self.p_part
            .get(i)
            .copied()
            .unwrap_or(if self.truncated { 0 } else { PPartEntry::MAX })
    }

    /// Checks whether the profile function is valid
    pub fn is_valid(&self) -> bool {
        for (i, &hi) in self.p_part.iter().enumerate() {
            for (j, &hj) in self.p_part.iter().enumerate().skip(i + 1) {
                if hi > (j - i) as PPartEntry + hj && self.p_part[j - i - 1] > hj {
                    return false;
                }
            }
        }
        if self.truncated {
            let len = self.p_part.len();
            for (i, &hi) in self.p_part.iter().enumerate() {
                if hi > (len - i) as PPartEntry {
                    return false;
                }
            }
        }
        if self.q_part != !0 {
            for i in BitflagIterator::set_bit_iterator(!self.q_part as u64) {
                for j in 0..i {
                    if (self.q_part >> j) & 1 == 1 && self.get_p_part(i - j - 1) > j as PPartEntry {
                        return false;
                    }
                }
            }
        }
        true
    }

    /// Whether the profile is that of A(n). This is relevant since A(n) is generated by P(p^n) and
    /// β but a general subalgebra is not.
    pub fn is_an(&self, generic: bool) -> bool {
        if *self == Self::default() {
            return true;
        }
        if !self.truncated {
            return false;
        }
        if self.p_part.len() != self.p_part[0] as usize {
            return false;
        }
        if generic && self.q_part != (1 << (self.p_part.len() + 1)) - 1 {
            return false;
        }
        true
    }
}

impl Default for MilnorProfile {
    fn default() -> Self {
        Self {
            truncated: false,
            q_part: !0,
            p_part: Vec::new(),
        }
    }
}

pub type PPartEntry = u32;

/// The exponent sequence $(r_1, r_2, \ldots)$ of a Milnor basis element $P(r_1, r_2, \ldots)$,
/// bit-packed into a single `u64`.
///
/// Entry $r_{i+1}$ occupies `WIDTHS[i]` bits starting at bit `SHIFTS[i]` (both private). The
/// widths are forced by the degree bound: at $p = 2$ the internal degree of $P(R)$ is
/// $\sum_i r_i (2^i - 1)$ and every term is non-negative, so an element of degree at most
/// [`Self::MAX_DEGREE`] has $r_i \le \mathrm{MAX\\_DEGREE}/(2^i - 1)$. At an odd prime the same
/// argument bounds $r_i$ by that quantity divided by $q = 2(p-1)$, so the $p = 2$ widths are valid
/// for every prime and this type is prime-agnostic.
///
/// Trailing zeros are not represented: $P(2, 1)$ and $P(2, 1, 0)$ have the same packed value. That
/// is what makes the packed value a canonical key, and it makes [`Self::len`] the position of the
/// highest non-zero entry rather than a stored field.
///
/// # Invariant
///
/// Every entry fits in its field. This holds for any element of degree at most
/// [`Self::MAX_DEGREE`], which [`MilnorAlgebra::compute_basis`] enforces up front, so the packing
/// can never silently truncate. [`Self::set`] asserts it anyway, and [`Self::try_from_slice`]
/// reports failure instead of panicking for input that has not been through that gate.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct PPart(u64);

impl PPart {
    /// The largest internal degree whose exponent sequences are guaranteed to fit.
    ///
    /// This is the largest bound for which the field widths sum to at most 64. It is far beyond
    /// anything reachable — the Milnor algebra already has over 5 million basis elements below
    /// degree 300 — and exceeds the degree 1536 the previous hand-rolled packing assumed.
    pub const MAX_DEGREE: i32 = 2045;

    /// The number of entries that can be stored. This equals `fp`'s `MAX_MULTINOMIAL_LEN`, which
    /// already bounds the length of the $\xi$-degree table, so it is not a new restriction.
    pub const MAX_LEN: usize = 10;

    /// The length of the layout tables. This is [`Self::MAX_LEN`] rounded up to a power of two so
    /// that [`Self::entry`] can mask its index instead of bounds-checking it; entries at or past
    /// `MAX_LEN` are given width 0, so they read as zero.
    const TABLE_LEN: usize = 16;

    /// `WIDTHS[i]` is the number of bits holding $r_{i+1}$: the number of bits needed to represent
    /// `MAX_DEGREE / (2^(i+1) - 1)`.
    const WIDTHS: [u32; Self::TABLE_LEN] = [11, 10, 9, 8, 7, 6, 5, 4, 3, 1, 0, 0, 0, 0, 0, 0];

    /// `SHIFTS[i]` is the bit offset of entry `i`; `SHIFTS[MAX_LEN]` is the total width, 64.
    const SHIFTS: [u32; Self::TABLE_LEN] = {
        let mut shifts = [0; Self::TABLE_LEN];
        let mut i = 0;
        while i < Self::MAX_LEN {
            shifts[i + 1] = shifts[i] + Self::WIDTHS[i];
            i += 1;
        }
        shifts
    };

    /// `FIELD_OF_BIT[b]` is the index of the entry owning bit `b`, letting [`Self::len`] turn a
    /// `leading_zeros` into an entry index without looping.
    const FIELD_OF_BIT: [u8; 64] = {
        let mut table = [0; 64];
        let mut i = 0;
        while i < Self::MAX_LEN {
            let mut b = Self::SHIFTS[i];
            while b < Self::SHIFTS[i + 1] {
                table[b as usize] = i as u8;
                b += 1;
            }
            i += 1;
        }
        table
    };

    /// The largest value entry `i` can hold.
    pub const fn max_entry(i: usize) -> PPartEntry {
        ((1u64 << Self::WIDTHS[i]) - 1) as PPartEntry
    }

    /// The number of bits holding entry `i`. Together with [`Self::shift`] this lets callers build
    /// a mask over [`Self::bits`] directly, e.g. to test many entries in one comparison.
    pub const fn width(i: usize) -> u32 {
        Self::WIDTHS[i]
    }

    /// The bit offset of entry `i` within [`Self::bits`].
    pub const fn shift(i: usize) -> u32 {
        Self::SHIFTS[i]
    }

    const fn mask(i: usize) -> u64 {
        ((1u64 << Self::WIDTHS[i]) - 1) << Self::SHIFTS[i]
    }

    pub const fn zero() -> Self {
        Self(0)
    }

    /// The raw packed value. Two exponent sequences are equal exactly when their bits are, so this
    /// is a complete hash key, and it can be compared against a packed mask in one operation (see
    /// `MilnorSubalgebra::packed_signature` in `ext`).
    pub const fn bits(self) -> u64 {
        self.0
    }

    /// Reinterpret a raw packed value.
    ///
    /// Callers that assemble entries by shifting must uphold the type invariant themselves: each
    /// entry must lie within its field, which holds for any element of degree at most
    /// [`Self::MAX_DEGREE`]. This exists so hot loops can accumulate into a plain `u64` and store
    /// once, rather than read-modify-write through [`Self::set`] per entry.
    pub(crate) const fn from_bits(bits: u64) -> Self {
        Self(bits)
    }

    /// Entry `i`, for `i < TABLE_LEN`, with no bounds check.
    ///
    /// Masking the index keeps the table lookups in range without a branch. Entries in
    /// `MAX_LEN..TABLE_LEN` have width 0 and so read as zero, which is the right answer; an index
    /// at or beyond `TABLE_LEN` would silently wrap, which is why this is private and
    /// `debug_assert`ed. Callers in the multiplier are all bounded by `MAX_LEN`.
    #[inline]
    const fn entry(self, i: usize) -> PPartEntry {
        debug_assert!(i < Self::TABLE_LEN);
        let i = i & (Self::TABLE_LEN - 1);
        ((self.0 >> Self::SHIFTS[i]) & ((1 << Self::WIDTHS[i]) - 1)) as PPartEntry
    }

    /// Entry `i`, or 0 if `i` is past the end. Accepts any index.
    #[inline]
    pub const fn get(self, i: usize) -> PPartEntry {
        if i >= Self::MAX_LEN {
            return 0;
        }
        self.entry(i)
    }

    /// Set entry `i` to `v`.
    ///
    /// # Panics
    ///
    /// If `i >= MAX_LEN`, or `v` does not fit in entry `i`. Both are unreachable for elements of
    /// degree at most [`Self::MAX_DEGREE`].
    #[inline]
    pub fn set(&mut self, i: usize, v: PPartEntry) {
        assert!(i < Self::MAX_LEN, "p-part index {i} out of range");
        assert!(
            v <= Self::max_entry(i),
            "p-part entry {v} does not fit in the {} bits at index {i}",
            Self::WIDTHS[i],
        );
        self.0 = (self.0 & !Self::mask(i)) | ((v as u64) << Self::SHIFTS[i]);
    }

    /// The number of entries up to and including the last non-zero one.
    #[inline]
    pub const fn len(self) -> usize {
        if self.0 == 0 {
            0
        } else {
            Self::FIELD_OF_BIT[63 - self.0.leading_zeros() as usize] as usize + 1
        }
    }

    #[inline]
    pub const fn is_empty(self) -> bool {
        self.0 == 0
    }

    /// Zero every entry from `n` onwards, i.e. the packed form of `self[..n]`.
    #[inline]
    pub const fn truncate(self, n: usize) -> Self {
        if n >= Self::MAX_LEN {
            self
        } else {
            Self(self.0 & ((1 << Self::SHIFTS[n]) - 1))
        }
    }

    pub fn iter(self) -> impl DoubleEndedIterator<Item = PPartEntry> + ExactSizeIterator {
        (0..self.len()).map(move |i| self.get(i))
    }

    /// Pack `entries`, returning `None` if they do not fit. Use this for anything derived from
    /// user input; use [`Self::from_slice`] when the degree bound already guarantees a fit.
    pub fn try_from_slice(entries: &[PPartEntry]) -> Option<Self> {
        let mut result = Self::zero();
        for (i, &entry) in entries.iter().enumerate() {
            // A zero past the end is just padding, which the packed form drops anyway.
            if entry == 0 {
                continue;
            }
            if i >= Self::MAX_LEN || entry > Self::max_entry(i) {
                return None;
            }
            result.set(i, entry);
        }
        Some(result)
    }

    /// Pack `entries`, panicking if they do not fit.
    pub fn from_slice(entries: &[PPartEntry]) -> Self {
        Self::try_from_slice(entries).unwrap_or_else(|| {
            panic!(
                "p-part {entries:?} exceeds the degree {} bound",
                Self::MAX_DEGREE
            )
        })
    }
}

impl FromIterator<PPartEntry> for PPart {
    fn from_iter<I: IntoIterator<Item = PPartEntry>>(iter: I) -> Self {
        let mut result = Self::zero();
        for (i, entry) in iter.into_iter().enumerate() {
            if entry != 0 {
                result.set(i, entry);
            }
        }
        result
    }
}

impl std::fmt::Debug for PPart {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.debug_list().entries(self.iter()).finish()
    }
}

/// A Milnor basis element. This is `Copy` and entirely inline: 16 bytes, no heap.
#[derive(Debug, Clone, Copy, Default)]
pub struct MilnorBasisElement {
    pub q_part: u32,
    pub p_part: PPart,
    pub degree: i32,
}

impl MilnorBasisElement {
    fn from_p(p_part: PPart, degree: i32) -> Self {
        Self {
            q_part: 0,
            p_part,
            degree,
        }
    }

    fn excess(&self, p: ValidPrime) -> u32 {
        if p == 2 {
            self.p_part.iter().sum::<PPartEntry>()
        } else {
            self.q_part.count_ones() + 2 * self.p_part.iter().sum::<PPartEntry>()
        }
    }

    pub fn clone_into(&self, other: &mut Self) {
        *other = *self;
    }

    /// Update the degree component to the correct degree
    pub fn compute_degree(&mut self, p: ValidPrime) {
        let q = if p == 2 { 1 } else { 2 * (p.as_i32() - 1) };
        let xi_degrees = combinatorics::xi_degrees(p);
        let tau_degrees = combinatorics::tau_degrees(p);

        self.degree = q * std::iter::zip(xi_degrees, self.p_part.iter())
            .map(|(&a, b)| a * b as i32)
            .sum::<i32>()
            + BitflagIterator::set_bit_iterator(self.q_part as u64)
                .map(|k| tau_degrees[k])
                .sum::<i32>();
    }
}

impl std::cmp::PartialEq for MilnorBasisElement {
    fn eq(&self, other: &Self) -> bool {
        #[cfg(feature = "odd-primes")]
        return self.p_part == other.p_part && self.q_part == other.q_part;

        #[cfg(not(feature = "odd-primes"))]
        return self.p_part == other.p_part;
    }
}

impl std::cmp::Eq for MilnorBasisElement {}

impl std::hash::Hash for MilnorBasisElement {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        // The p-part is a single `u64`, so this is one hasher round rather than a pointer chase
        // plus a variable-length slice hash.
        self.p_part.bits().hash(state);
        #[cfg(feature = "odd-primes")]
        self.q_part.hash(state);
    }
}

impl std::fmt::Display for MilnorBasisElement {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        if self.degree == 0 {
            write!(f, "1")?;
            return Ok(());
        }
        if self.q_part != 0 {
            let q_part = BitflagIterator::set_bit_iterator(self.q_part as u64)
                .map(|idx| format!("Q_{idx}"))
                .format(" ");
            write!(f, "{q_part}")?;
        }
        if !self.p_part.is_empty() {
            if self.q_part != 0 {
                write!(f, " ")?;
            }
            write!(f, "P({})", self.p_part.iter().format(", "))?;
        }
        Ok(())
    }
}

/// A map from the basis elements of a single degree to their indices.
///
/// [`MilnorBasisElement`] hashes and compares on its p-part (and, at odd primes, its q-part), both
/// of which are now single machine words, so a plain `HashMap` is already the specialised form
/// this used to hand-roll for `p = 2`.
type MilnorHashMap<V> = HashMap<MilnorBasisElement, V>;

pub struct MilnorAlgebra {
    profile: MilnorProfile,
    p: ValidPrime,
    #[cfg(feature = "odd-primes")]
    generic: bool,

    unstable_enabled: bool,

    /// This is a list of possible P(R) of each degree, where `ppart_table[i]` contains elements of
    /// degree `q * i`.
    ppart_table: OnceVec<Vec<PPart>>,

    /// A list of all basis elements of each degree, constructed from [`Self::ppart_table`].
    ///
    /// Only populated when [`Self::stores_basis_table`] holds. At `p = 2` with unstable support
    /// off, the basis element at index `i` of degree `t` is exactly
    /// `MilnorBasisElement::from_p(ppart_table[t][i], t)`, so storing it repeats the p-part with a
    /// known q-part and degree bolted on -- 16 bytes per element, about a quarter of the algebra's
    /// footprint. [`Self::basis_element_from_index`] reconstructs it instead, which is free now
    /// that the type is `Copy` and fits in registers.
    basis_table: OnceVec<Vec<MilnorBasisElement>>,

    excess_table: OnceVec<Vec<usize>>,

    /// degree -> MilnorBasisElement -> index
    basis_element_to_index_map: OnceVec<MilnorHashMap<usize>>,

    #[cfg(feature = "cache-multiplication")]
    /// source_deg -> target_deg -> source_op -> target_op
    multiplication_table: OnceVec<OnceVec<Vec<Vec<FpVector>>>>,
}

impl std::fmt::Display for MilnorAlgebra {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "MilnorAlgebra(p={})", self.prime())
    }
}

impl MilnorAlgebra {
    pub fn new(p: ValidPrime, unstable_enabled: bool) -> Self {
        Self::new_with_profile(p, MilnorProfile::default(), unstable_enabled)
    }

    pub fn new_with_profile(p: ValidPrime, profile: MilnorProfile, unstable_enabled: bool) -> Self {
        assert!(profile.is_valid());
        Self {
            p,
            #[cfg(feature = "odd-primes")]
            generic: p != 2,
            unstable_enabled,
            profile,
            ppart_table: OnceVec::new(),
            basis_table: OnceVec::new(),
            excess_table: OnceVec::new(),
            basis_element_to_index_map: OnceVec::new(),
            #[cfg(feature = "cache-multiplication")]
            multiplication_table: OnceVec::new(),
        }
    }

    #[inline]
    pub fn generic(&self) -> bool {
        #[cfg(feature = "odd-primes")]
        {
            self.generic
        }

        #[cfg(not(feature = "odd-primes"))]
        {
            false
        }
    }

    pub fn q(&self) -> i32 {
        if self.generic() {
            2 * (self.prime().as_i32() - 1)
        } else {
            1
        }
    }

    pub fn profile(&self) -> &MilnorProfile {
        &self.profile
    }

    /// Whether the basis of each degree has to be stored rather than derived.
    ///
    /// At odd primes the q-part varies within a degree, and with unstable support enabled the
    /// basis is re-sorted by excess; in both cases the basis is not a re-wrapping of
    /// [`Self::ppart_table`] and must be kept.
    fn stores_basis_table(&self) -> bool {
        self.generic() || self.unstable_enabled
    }

    pub fn basis_element_from_index(&self, degree: i32, idx: usize) -> MilnorBasisElement {
        if self.stores_basis_table() {
            self.basis_table[degree as usize][idx]
        } else {
            MilnorBasisElement::from_p(self.ppart_table[degree as usize][idx], degree)
        }
    }

    pub fn try_basis_element_to_index(&self, elt: &MilnorBasisElement) -> Option<usize> {
        self.basis_element_to_index_map[elt.degree as usize]
            .get(elt)
            .copied()
    }

    pub fn basis_element_to_index(&self, elt: &MilnorBasisElement) -> usize {
        self.try_basis_element_to_index(elt)
            .unwrap_or_else(|| panic!("Didn't find element: {elt:?}"))
    }

    /// Gives a list of PPart's in degree `t`.
    pub fn ppart_table(&self, t: i32) -> &[PPart] {
        &self.ppart_table[t as usize]
    }
}

impl Algebra for MilnorAlgebra {
    fn prefix(&self) -> &str {
        "milnor"
    }

    fn magic(&self) -> u32 {
        (self.p << 16)
            + if self.profile.is_trivial() {
                0x8000
            } else {
                0x8001
            }
    }

    fn prime(&self) -> ValidPrime {
        self.p
    }

    fn default_filtration_one_products(&self) -> Vec<(String, i32, usize)> {
        let mut products = Vec::with_capacity(4);
        let max_degree = if self.generic() {
            if self.profile.q_part & 1 != 0 {
                products.push((
                    "a_0".to_string(),
                    MilnorBasisElement {
                        degree: 1,
                        q_part: 1,
                        p_part: PPart::zero(),
                    },
                ));
            }
            if (self.profile.p_part.is_empty() && !self.profile.truncated)
                || (!self.profile.p_part.is_empty() && self.profile.p_part[0] > 0)
            {
                products.push((
                    "h_0".to_string(),
                    MilnorBasisElement {
                        degree: (2 * self.prime() - 2) as i32,
                        q_part: 0,
                        p_part: PPart::from_iter([1]),
                    },
                ));
            }
            (2 * self.prime() - 2) as i32
        } else {
            let mut max = 4;
            if !self.profile.p_part.is_empty() {
                max = std::cmp::min(4, self.profile.p_part[0]);
            } else if self.profile.truncated {
                max = 0;
            }
            for i in 0..max {
                let degree = 1 << i; // degree is 2^hi
                products.push((
                    format!("h_{i}"),
                    MilnorBasisElement {
                        degree,
                        q_part: 0,
                        p_part: PPart::from_iter([1 << i]),
                    },
                ));
            }
            1 << 3
        };
        self.compute_basis(max_degree + 1);

        products
            .into_iter()
            .map(|(name, b)| (name, b.degree, self.basis_element_to_index(&b)))
            .collect()
    }

    fn compute_basis(&self, max_degree: i32) {
        // This is the single gate that makes [`PPart`]'s packing safe: past this degree an
        // exponent could outgrow its field. Everything downstream may then assume entries fit.
        assert!(
            max_degree <= PPart::MAX_DEGREE,
            "Milnor basis elements are only supported up to degree {}, got {max_degree}",
            PPart::MAX_DEGREE,
        );
        self.compute_ppart(max_degree);

        if self.generic() {
            self.generate_basis_generic(max_degree);
        } else {
            self.generate_basis_2(max_degree);
        }

        // Populate hash map
        self.basis_element_to_index_map
            .extend(max_degree as usize, |d| {
                let mut map = MilnorHashMap::default();
                let dim = self.dimension(d as i32);
                map.reserve(dim);
                for i in 0..dim {
                    let b = self.basis_element_from_index(d as i32, i);
                    assert!(map.insert(b, i).is_none(), "Duplicate entry for {b}");
                }
                map
            });

        #[cfg(feature = "cache-multiplication")]
        {
            self.multiplication_table
                .extend(max_degree as usize, |_| OnceVec::new());

            for d in 0..=max_degree as usize {
                self.multiplication_table[d].extend(max_degree as usize - d, |e| {
                    (0..self.dimension(d as i32))
                        .map(|i| {
                            (0..self.dimension(e as i32))
                                .map(|j| {
                                    let mut res =
                                        FpVector::new(self.prime(), self.dimension((d + e) as i32));
                                    self.multiply(
                                        res.as_slice_mut(),
                                        1,
                                        self.basis_element_from_index(d as i32, i),
                                        self.basis_element_from_index(e as i32, j),
                                    );
                                    res
                                })
                                .collect::<Vec<_>>()
                        })
                        .collect::<Vec<_>>()
                });
            }
        }

        if self.unstable_enabled {
            self.generate_excess_table(max_degree);
        }
    }

    fn dimension(&self, degree: i32) -> usize {
        if degree < 0 {
            return 0;
        }
        if self.stores_basis_table() {
            self.basis_table[degree as usize].len()
        } else {
            self.ppart_table[degree as usize].len()
        }
    }

    #[cfg(not(feature = "cache-multiplication"))]
    fn multiply_basis_elements(
        &self,
        result: FpSliceMut,
        coef: u32,
        r_degree: i32,
        r_idx: usize,
        s_degree: i32,
        s_idx: usize,
    ) {
        self.multiply(
            result,
            coef,
            self.basis_element_from_index(r_degree, r_idx),
            self.basis_element_from_index(s_degree, s_idx),
        );
    }

    #[cfg(feature = "cache-multiplication")]
    fn multiply_basis_elements(
        &self,
        mut result: FpSliceMut,
        coef: u32,
        r_degree: i32,
        r_idx: usize,
        s_degree: i32,
        s_idx: usize,
    ) {
        result.add(
            self.multiplication_table[r_degree as usize][s_degree as usize][r_idx][s_idx]
                .as_slice(),
            coef,
        );
    }

    fn multiply_basis_element_by_element(
        &self,
        mut result: FpSliceMut,
        coeff: u32,
        r_degree: i32,
        r_idx: usize,
        s_degree: i32,
        s: FpSlice,
    ) {
        let p = self.prime();
        let r = self.basis_element_from_index(r_degree, r_idx);
        PPartAllocation::with_local(|mut allocation| {
            for (i, v) in s.iter_nonzero() {
                allocation = self.multiply_with_allocation(
                    result.copy(),
                    (coeff * v) % p,
                    r,
                    self.basis_element_from_index(s_degree, i),
                    i32::MAX,
                    allocation,
                );
            }
            allocation
        });
    }

    fn multiply_element_by_element(
        &self,
        mut res: FpSliceMut,
        coef: u32,
        r_deg: i32,
        r: FpSlice,
        s_deg: i32,
        s: FpSlice,
    ) {
        PPartAllocation::with_local(|mut allocation| {
            for (i, c) in r.iter_nonzero() {
                allocation = self.multiply_basis_by_element_with_allocation(
                    res.copy(),
                    coef * c,
                    self.basis_element_from_index(r_deg, i),
                    s_deg,
                    s,
                    allocation,
                );
            }
            allocation
        })
    }

    fn basis_element_to_string(&self, degree: i32, idx: usize) -> String {
        format!("{}", self.basis_element_from_index(degree, idx))
    }

    fn basis_element_from_string(&self, elt: &str) -> Option<(i32, usize)> {
        use nom::{
            Parser,
            branch::alt,
            bytes::complete::tag,
            character::complete::char,
            combinator::{map, opt},
            multi::{many0, separated_list1},
            sequence::preceded,
        };

        use crate::steenrod_parser::{brackets, digits, p_or_sq};

        let p = self.prime();

        let mut parser = alt((
            map(char('1'), |_| Some((0, 0))),
            map(char('b'), |_| Some((1, 0))),
            map(preceded(p_or_sq, digits), |i| self.try_beps_pn(0, i)),
            map(
                (tag("P^"), digits, char('_'), digits::<usize>),
                |(_, s, _, t)| {
                    if t == 0 || t >= combinatorics::xi_degrees(p).len() {
                        return None;
                    }
                    let entry: PPartEntry = p.as_u32().checked_pow(s)?;
                    if entry > PPart::max_entry(t - 1) {
                        return None;
                    }
                    let degree = (entry as i32)
                        .checked_mul(self.q())?
                        .checked_mul(combinatorics::xi_degrees(p)[t])?;
                    if degree > PPart::MAX_DEGREE {
                        return None;
                    }
                    let mut p_part = PPart::zero();
                    p_part.set(t - 1, entry);
                    let elt = MilnorBasisElement {
                        degree,
                        q_part: 0,
                        p_part,
                    };
                    self.compute_basis(degree);
                    self.try_basis_element_to_index(&elt)
                        .map(|idx| (degree, idx))
                },
            ),
            map(
                (
                    many0(preceded(tag("Q_"), digits::<u32>)),
                    opt(preceded(
                        char('P'),
                        brackets(separated_list1(char(','), digits)),
                    )),
                ),
                |(q_list, p_list)| {
                    let q_part = q_list.into_iter().fold(0, |acc, q| acc + (1 << q));
                    let p_part = PPart::try_from_slice(&p_list.unwrap_or_default())?;
                    let mut elt = MilnorBasisElement {
                        degree: 0,
                        q_part,
                        p_part,
                    };
                    elt.compute_degree(p);
                    if elt.degree > PPart::MAX_DEGREE {
                        return None;
                    }
                    self.compute_basis(elt.degree);

                    self.try_basis_element_to_index(&elt)
                        .map(|idx| (elt.degree, idx))
                },
            ),
        ));

        if let Ok(("", res)) = parser.parse(elt) {
            res
        } else {
            None
        }
    }
}

impl UnstableAlgebra for MilnorAlgebra {
    fn dimension_unstable(&self, degree: i32, excess: i32) -> usize {
        if degree < 0 || excess < 0 {
            0
        } else if excess < degree {
            self.excess_table[degree as usize][excess as usize]
        } else {
            self.dimension(degree)
        }
    }

    fn multiply_basis_elements_unstable(
        &self,
        result: FpSliceMut,
        coeff: u32,
        r_degree: i32,
        r_index: usize,
        s_degree: i32,
        s_index: usize,
        excess: i32,
    ) {
        let m1 = self.basis_element_from_index(r_degree, r_index);
        let m2 = self.basis_element_from_index(s_degree, s_index);
        PPartAllocation::with_local(|allocation| {
            self.multiply_with_allocation(result, coeff, m1, m2, excess, allocation)
        });
    }
}

impl GeneratedAlgebra for MilnorAlgebra {
    fn generator_to_string(&self, degree: i32, idx: usize) -> String {
        if self.generic() {
            if degree == 1 {
                return "b".to_string();
            }
            let elt = self.basis_element_from_index(degree, idx);
            let len = elt.p_part.len();
            if elt.q_part != 0 {
                elt.to_string()
            } else if len == 1 {
                format!("P{}", degree / self.q())
            } else {
                format!(
                    "P^{}_{}",
                    degree / (self.q() * combinatorics::xi_degrees(self.prime())[len - 1]),
                    len
                )
            }
        } else {
            let elt = self.basis_element_from_index(degree, idx);
            let len = elt.p_part.len();
            if len == 1 {
                format!("Sq{degree}")
            } else {
                format!(
                    "P^{}_{}",
                    degree / (combinatorics::xi_degrees(self.prime())[len - 1]),
                    len
                )
            }
        }
    }

    fn generators(&self, degree: i32) -> Vec<usize> {
        if degree <= 0 {
            return vec![];
        } else if degree == 1 {
            return vec![0]; // Q_0
        }

        let p = self.prime();

        // Check for the Q_k
        if self.generic() && degree % 2 == 1 {
            if self.profile.is_an(true) {
                return vec![];
            }

            // If this is 2p^k - 1, then return Q_k
            if let (k, 2) = factor_pk(p, degree as u32 + 1) {
                let q_part = 1 << k;
                if self.profile.q_part & q_part != 0 {
                    return vec![self.basis_element_to_index(&MilnorBasisElement {
                        degree,
                        q_part,
                        p_part: PPart::zero(),
                    })];
                }
            }
            return vec![];
        }

        if self.profile.is_an(self.generic()) {
            // Look for P(p^k), which has degree p^k q.
            let q = self.q() as u32;
            if !(degree as u32).is_multiple_of(q) {
                return vec![];
            }
            if let (k, 1) = factor_pk(p, degree as u32 / q)
                && (k as PPartEntry) < self.profile.get_p_part(0)
            {
                return vec![self.basis_element_to_index(&MilnorBasisElement {
                    degree,
                    q_part: 0,
                    p_part: PPart::from_iter([(degree as u32 / q) as PPartEntry]),
                })];
            }
            vec![]
        } else {
            // Look for P(0, ..., 0, p^k), which has degree (2p^j - 2) p^k.
            let (k, rem) = factor_pk(p, degree as u32);

            let reduced = if self.generic() {
                // rem must be even because degree is even
                (rem + 2) / 2
            } else {
                rem + 1
            };

            if let (j, 1) = factor_pk(p, reduced) {
                if self.profile.get_p_part(j as usize - 1) <= k as PPartEntry {
                    return vec![];
                }
                let mut p_part = PPart::zero();
                p_part.set(j as usize - 1, p.pow(k) as PPartEntry);
                return vec![self.basis_element_to_index(&MilnorBasisElement {
                    degree,
                    q_part: 0,
                    p_part,
                })];
            }
            vec![]
        }
    }

    fn decompose_basis_element(
        &self,
        degree: i32,
        idx: usize,
    ) -> Vec<(u32, (i32, usize), (i32, usize))> {
        let basis = self.basis_element_from_index(degree, idx);
        // If qpart = 0, return self
        if basis.q_part == 0 {
            self.decompose_basis_element_ppart(degree, idx)
        } else {
            self.decompose_basis_element_qpart(degree, idx)
        }
    }

    fn generating_relations(&self, degree: i32) -> Vec<Vec<(u32, (i32, usize), (i32, usize))>> {
        if self.generic() && degree == 2 {
            // beta^2 = 0 is an edge case
            return vec![vec![(1, (1, 0), (1, 0))]];
        }
        let p = self.prime();
        let inadmissible_pairs = combinatorics::inadmissible_pairs(p, self.generic(), degree);
        let mut result = Vec::new();
        for (x, b, y) in inadmissible_pairs {
            let mut relation = Vec::new();
            // Adem relation. Sometimes these don't exist because of profiles. Then just ignore it.
            (|| {
                let (first_degree, first_index) = self.try_beps_pn(0, x as PPartEntry)?;
                let (second_degree, second_index) = self.try_beps_pn(b, y as PPartEntry)?;
                relation.push((
                    p - 1,
                    (first_degree, first_index),
                    (second_degree, second_index),
                ));
                for e1 in 0..=b {
                    let e2 = b - e1;
                    // e1 and e2 determine where a bockstein shows up.
                    // e1 determines whether a bockstein shows up in front
                    // e2 determines whether a bockstein shows up in middle
                    // So our output term looks like b^{e1} P^{x+y-j} b^{e2} P^{j}
                    for j in 0..=x / p {
                        let c = combinatorics::adem_relation_coefficient(p, x, y, j, e1, e2);
                        if c == 0 {
                            continue;
                        }
                        if j == 0 {
                            relation.push((
                                c,
                                self.try_beps_pn(e1, (x + y) as PPartEntry)?,
                                (e2 as i32, 0),
                            ));
                            continue;
                        }
                        let first_sq = self.try_beps_pn(e1, (x + y - j) as PPartEntry)?;
                        let second_sq = self.try_beps_pn(e2, j as PPartEntry)?;
                        relation.push((c, first_sq, second_sq));
                    }
                }
                result.push(relation);
                Some(())
            })();
        }
        result
    }
}

// Compute basis functions
impl MilnorAlgebra {
    fn compute_ppart(&self, max_degree: i32) {
        self.ppart_table.extend(0, |_| vec![PPart::zero()]);

        let p = self.prime().as_i32();
        let q = if p == 2 { 1 } else { 2 * p - 2 };
        let new_deg = max_degree / q;

        let xi_degrees = combinatorics::xi_degrees(self.prime());
        let mut profile_list = Vec::with_capacity(xi_degrees.len());
        for i in 0..xi_degrees.len() {
            if i < self.profile.p_part.len() {
                profile_list.push((self.prime().pow(self.profile.p_part[i]) - 1) as PPartEntry);
            } else if self.profile.truncated {
                profile_list.push(0);
            } else {
                profile_list.push(PPartEntry::MAX);
            }
        }

        self.ppart_table.extend(new_deg as usize, |d| {
            let d = d as i32;
            let mut new_row = Vec::new(); // Improve this
            for i in 0..xi_degrees.len() {
                if xi_degrees[i] > d {
                    break;
                }
                if profile_list[i] == 0 {
                    continue;
                }

                let rem = (d - xi_degrees[i]) as usize;
                for &old in &self.ppart_table[rem] {
                    // ppart_table[rem] is arranged in increasing order of highest
                    // xi_i. If we get something too large, we may abort;
                    if old.len() > i + 1 {
                        break;
                    }
                    // `profile_list[i]` is non-zero here, so `old.get(i) == profile_list[i]`
                    // already implies `old.len() == i + 1`.
                    if old.get(i) == profile_list[i] {
                        continue;
                    }
                    let mut new = old;
                    new.set(i, old.get(i) + 1);
                    new_row.push(new);
                }
            }
            new_row
        });
    }

    fn generate_basis_generic(&self, max_degree: i32) {
        let q = 2 * self.prime() - 2;
        let tau_degrees = combinatorics::tau_degrees(self.prime());

        self.basis_table.extend(max_degree as usize, |d| {
            let mut table = Vec::new();
            let residue = d as u32 % q;

            for q_part in 0u32.. {
                if q_part.count_ones() % q != residue {
                    continue;
                }

                let mut q_degree = 0;
                let mut bs = q_part;
                for &entry in tau_degrees {
                    q_degree += entry * (bs & 1) as i32;
                    bs >>= 1;
                    if bs == 0 {
                        break;
                    }
                }

                if q_degree > d as i32 {
                    break;
                }

                if q_part & !self.profile.q_part != 0 {
                    continue;
                }

                table.extend(
                    self.ppart_table[(d - q_degree as usize) / q as usize]
                        .iter()
                        .map(|&p_part| MilnorBasisElement {
                            p_part,
                            q_part,
                            degree: d as i32,
                        }),
                );
            }
            if self.unstable_enabled {
                table.sort_by_cached_key(|e| e.excess(self.p));
            }
            table
        });
    }

    fn generate_basis_2(&self, max_degree: i32) {
        if !self.stores_basis_table() {
            // Derived on demand from `ppart_table`; see the field docs.
            return;
        }
        self.basis_table.extend(max_degree as usize, |d| {
            let mut table: Vec<_> = self.ppart_table[d]
                .iter()
                .map(|&p| MilnorBasisElement::from_p(p, d as i32))
                .collect();
            table.sort_by_cached_key(|e| e.excess(fp::prime::TWO));
            table
        });
    }

    fn generate_excess_table(&self, max_degree: i32) {
        let p = self.prime();
        self.excess_table.extend(max_degree as usize, |n| {
            let mut new_entry = Vec::with_capacity(n);
            let mut cur_excess = 0;
            for (i, elt) in self.basis_table[n].iter().enumerate() {
                let excess = elt.excess(p);
                for _ in cur_excess..excess {
                    new_entry.push(i);
                }
                cur_excess = excess;
            }
            let dim = self.dimension(n as i32);
            for _ in cur_excess..n as u32 {
                new_entry.push(dim);
            }
            new_entry
        });
    }
}

// Multiplication logic
impl MilnorAlgebra {
    /// Return the degree and index of $Q_1^e P(x)$, or `None` if the element is not present
    /// (e.g. out of range or excluded by the profile).
    pub fn try_beps_pn(&self, e: u32, x: PPartEntry) -> Option<(i32, usize)> {
        // Bound `x` first: `q * x + e` overflows for a large `x`, so the degree cannot be
        // computed before it has been rejected.
        if x > PPart::max_entry(0) {
            return None;
        }
        let q = self.q() as u32;
        let degree = (q * x + e) as i32;
        if degree > PPart::MAX_DEGREE {
            return None;
        }
        self.compute_basis(degree);
        self.try_basis_element_to_index(&MilnorBasisElement {
            degree,
            q_part: e,
            p_part: PPart::from_iter([x]),
        })
        .map(|index| (degree, index))
    }

    /// Return the degree and index of $Q_1^e P(x)$.
    pub fn beps_pn(&self, e: u32, x: PPartEntry) -> (i32, usize) {
        self.try_beps_pn(e, x).unwrap()
    }

    fn multiply_qpart(&self, m1: MilnorBasisElement, f: u32) -> Vec<(u32, MilnorBasisElement)> {
        let mut new_result: Vec<(u32, MilnorBasisElement)> = vec![(1, m1)];
        let mut old_result: Vec<(u32, MilnorBasisElement)> = Vec::new();

        for k in BitflagIterator::set_bit_iterator(f as u64) {
            let k = k as u32;
            let pk = self.p.pow(k) as PPartEntry;
            std::mem::swap(&mut new_result, &mut old_result);
            new_result.clear();

            // We implement the formula
            // P(R) Q_k = Q_k P^R + Q_{k+1} P(R - p^k e_1) + Q_{k+2} P(R - p^k e_2) +
            // ... + Q_{k + i} P(R - p^k e_i) + ...
            // where e_i is the vector with value 1 in entry i and 0 otherwise (in the above
            // formula, the first xi is xi_1, hence the offset below). If R - p^k e_i has a
            // negative entry, the term is 0.
            //
            // We also use the fact that Q_k Q_j = -Q_j Q_k
            for (coef, term) in &old_result {
                for i in 0..=term.p_part.len() {
                    // If there is already Q_{k+i} on the other side, the result is 0
                    if term.q_part & (1 << (k + i as u32)) != 0 {
                        continue;
                    }
                    let mut new_p = term.p_part;
                    if i > 0 {
                        // Check if R - p^k e_i < 0. Only do this from the first term onwards.
                        let entry = new_p.get(i - 1);
                        if entry < pk {
                            continue;
                        }
                        new_p.set(i - 1, entry - pk);
                    }

                    // Now calculate the number of Q's we are moving past
                    let larger_q = (term.q_part >> (k + i as u32 + 1)).count_ones();

                    // Trailing zeros are not represented in a packed p-part, so there is nothing
                    // to trim here.
                    // Now put everything together
                    let m = MilnorBasisElement {
                        p_part: new_p,
                        q_part: term.q_part | (1 << (k + i as u32)),
                        degree: 0, // we don't really care about the degree here. The final degree of the whole calculation is known a priori
                    };
                    let c = if larger_q.is_multiple_of(2) {
                        *coef
                    } else {
                        *coef * (self.prime() - 1)
                    };

                    new_result.push((c, m));
                }
            }
        }
        new_result
    }

    pub fn multiply(
        &self,
        res: FpSliceMut,
        coef: u32,
        m1: MilnorBasisElement,
        m2: MilnorBasisElement,
    ) {
        PPartAllocation::with_local(|allocation| {
            self.multiply_with_allocation(res, coef, m1, m2, i32::MAX, allocation)
        });
    }

    pub fn multiply_with_allocation(
        &self,
        mut res: FpSliceMut,
        coef: u32,
        m1: MilnorBasisElement,
        m2: MilnorBasisElement,
        excess: i32,
        mut allocation: PPartAllocation,
    ) -> PPartAllocation {
        let target_deg = m1.degree + m2.degree;
        if self.generic() {
            let m1f = self.multiply_qpart(m1, m2.q_part);
            for (cc, basis) in m1f {
                let mut multiplier = PPartMultiplier::<false>::new_from_allocation(
                    self.prime(),
                    basis.p_part,
                    m2.p_part,
                    allocation,
                    basis.q_part,
                    target_deg,
                );

                while let Some(c) = multiplier.next() {
                    let idx = self.basis_element_to_index(&multiplier.ans);
                    if idx < self.dimension_unstable(target_deg, excess) {
                        res.add_basis_element(idx, c * cc * coef);
                    }
                }
                allocation = multiplier.into_allocation()
            }
        } else {
            let mut multiplier = PPartMultiplier::<false>::new_from_allocation(
                self.prime(),
                m1.p_part,
                m2.p_part,
                allocation,
                0,
                target_deg,
            );

            while let Some(c) = multiplier.next() {
                let idx = self.basis_element_to_index(&multiplier.ans);
                if idx < self.dimension_unstable(target_deg, excess) {
                    res.add_basis_element(idx, c * coef);
                }
            }
            allocation = multiplier.into_allocation()
        }
        allocation
    }

    pub fn multiply_basis_by_element(
        &self,
        res: FpSliceMut,
        coef: u32,
        m1: MilnorBasisElement,
        s_deg: i32,
        s: FpSlice,
    ) {
        PPartAllocation::with_local(|allocation| {
            self.multiply_basis_by_element_with_allocation(res, coef, m1, s_deg, s, allocation)
        });
    }

    fn multiply_basis_by_element_with_allocation(
        &self,
        mut res: FpSliceMut,
        coef: u32,
        m1: MilnorBasisElement,
        s_deg: i32,
        s: FpSlice,
        mut allocation: PPartAllocation,
    ) -> PPartAllocation {
        for (i, c) in s.iter_nonzero() {
            allocation = self.multiply_with_allocation(
                res.copy(),
                coef * c,
                m1,
                self.basis_element_from_index(s_deg, i),
                i32::MAX,
                allocation,
            );
        }
        allocation
    }
}

#[derive(Debug, Default)]
struct Matrix2D {
    cols: usize,
    inner: Vec<PPartEntry>,
}

impl std::fmt::Display for Matrix2D {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        for i in 0..self.inner.len() / self.cols {
            writeln!(f, "{:?}", &self[i][0..self.cols])?;
        }
        Ok(())
    }
}

impl Matrix2D {
    fn reset(&mut self, rows: usize, cols: usize) {
        self.cols = cols;
        self.inner.clear();
        self.inner.resize(rows * cols, 0);
    }
}

impl Matrix2D {
    fn with_capacity(rows: usize, cols: usize) -> Self {
        Self {
            cols: 0,
            inner: Vec::with_capacity(rows * cols),
        }
    }
}

impl std::ops::Index<usize> for Matrix2D {
    type Output = [PPartEntry];

    fn index(&self, row: usize) -> &Self::Output {
        // Computing the end point is fairly expensive and only serves as a safety check...
        &self.inner[row * self.cols..]
    }
}

impl std::ops::IndexMut<usize> for Matrix2D {
    fn index_mut(&mut self, row: usize) -> &mut Self::Output {
        &mut self.inner[row * self.cols..]
    }
}

/// The parts of a PPartMultiplier that involve heap allocation.
///
/// This lets us reuse the allocation across multiple different multipliers. Reusing the whole
/// PPartMultiplier is finicky but doable due to lifetime issues. However, it appears to be less
/// performant.
#[derive(Default)]
pub struct PPartAllocation {
    m: Matrix2D,
    #[cfg(feature = "odd-primes")]
    diagonal: Vec<PPartEntry>,
}

thread_local! {
    static ALLOCATION: Cell<PPartAllocation> = Cell::new(PPartAllocation::with_capacity(9));
}

impl PPartAllocation {
    /// This creates a PPartAllocation with enough capacity to handle mulitiply elements with
    /// of total degree < 2^n - ε at p = 2.
    pub fn with_capacity(n: usize) -> Self {
        Self {
            m: Matrix2D::with_capacity(n + 1, n),
            #[cfg(feature = "odd-primes")]
            diagonal: Vec::with_capacity(n),
        }
    }

    pub fn with_local(f: impl FnOnce(Self) -> Self) {
        ALLOCATION.with(|alloc| {
            alloc.set(f(alloc.take()));
        });
    }
}

#[allow(non_snake_case)]
pub struct PPartMultiplier<const MOD4: bool> {
    p: ValidPrime,
    M: Matrix2D,
    r: PPart,
    rows: usize,
    cols: usize,
    diag_num: usize,
    init: bool,
    pub ans: MilnorBasisElement,
    #[cfg(feature = "odd-primes")]
    diagonal: Vec<PPartEntry>,
}

#[allow(non_snake_case)]
impl<const MOD4: bool> PPartMultiplier<MOD4> {
    fn prime(&self) -> ValidPrime {
        self.p
    }

    #[allow(unused_mut)] // Mut is only used with odd primes
    pub fn new_from_allocation(
        p: ValidPrime,
        r: PPart,
        s: PPart,
        mut allocation: PPartAllocation,
        q_part: u32,
        degree: i32,
    ) -> Self {
        if MOD4 {
            assert_eq!(p, 2);
        }
        let rows = r.len() + 1;
        let cols = s.len() + 1;
        let diag_num = r.len() + s.len();
        #[cfg(feature = "odd-primes")]
        {
            allocation.diagonal.clear();
            allocation.diagonal.reserve_exact(std::cmp::max(rows, cols));
        }

        let mut M = allocation.m;
        M.reset(rows, cols);

        for i in 1..rows {
            M[i][0] = r.entry(i - 1);
        }
        for k in 1..cols {
            M[0][k] = s.entry(k - 1);
        }

        let ans = MilnorBasisElement {
            q_part,
            p_part: PPart::zero(),
            degree,
        };
        Self {
            #[cfg(feature = "odd-primes")]
            diagonal: allocation.diagonal,
            p,
            M,
            r,
            rows,
            cols,
            diag_num,
            ans,
            init: true,
        }
    }

    pub fn into_allocation(self) -> PPartAllocation {
        PPartAllocation {
            m: self.M,
            #[cfg(feature = "odd-primes")]
            diagonal: self.diagonal,
        }
    }

    /// This compute the first l > k such that (sum + l) choose l != 0 mod p, stopping if we reach
    /// max + 1. This is useful for incrementing the matrix.
    ///
    /// TODO: Improve odd prime performance
    fn next_val(&self, sum: PPartEntry, k: PPartEntry, max: PPartEntry) -> PPartEntry {
        match self.prime().as_u32() {
            2 => {
                if MOD4 {
                    // x.count_ones() + y.count_ones() - (x + y).count_ones() is the number of
                    // carries when adding x to y.
                    //
                    // The p-adic valuation of (n + r) choose r is the number of carries when
                    // adding r to n in base p.
                    (k + 1..max + 1)
                        .find(|&l| {
                            sum & l == 0
                                || (sum.count_ones() + l.count_ones()) - (sum + l).count_ones() == 1
                        })
                        .unwrap_or(max + 1)
                } else {
                    ((k | sum) + 1) & !sum
                }
            }
            _ => (k + 1..max + 1)
                .find(|&l| !PPartEntry::binomial_odd_is_zero(self.prime(), sum + l, l))
                .unwrap_or(max + 1),
        }
    }

    /// We have a matrix of the form
    ///    | s₁  s₂  s₃ ...
    /// --------------------
    /// r₁ |
    /// r₂ |     x_{ij}
    /// r₃ |
    ///
    /// We think of ourselves as modifiying the center pieces x_{ij}, while the r_i's and s_j's are
    /// only there to ensure the x_{ij}'s don't get too big. The idea is to sweep through the
    /// matrix row by row, from top-to-bottom, and left-to-right. In each pass, we find the first
    /// entry that can be incremented. We then increment it and zero out all the entries that
    /// appear before it. This will give us all valid entries.
    fn update(&mut self) -> bool {
        for i in 1..self.rows {
            // total is sum x_{ij} p^j up to the jth column
            let mut total = self.M[i][0];
            let mut p_to_the_j = 1;
            for j in 1..self.cols {
                p_to_the_j *= self.prime().as_u32() as PPartEntry;
                if total < p_to_the_j {
                    // We don't have enough weight left in the entries above this one in the column to increment this cell.
                    // Add the weight from this cell to the total, we can use it to increment a cell lower down.
                    total += self.M[i][j] * p_to_the_j;
                    continue;
                }
                let col_sum: PPartEntry = (0..i).map(|k| self.M[k][j]).sum();
                if col_sum == 0 {
                    total += self.M[i][j] * p_to_the_j;
                    continue;
                }

                let max_inc = std::cmp::min(col_sum, total / p_to_the_j);

                // Compute the sum of entries along the diagonal to the bottom-left
                let mut sum = 0;
                for c in (i + j + 1).saturating_sub(self.rows)..j {
                    sum += self.M[i + j - c][c];
                }

                // Find the next possible value we can increment M[i][j] to without setting the
                // coefficient to 0. The coefficient is the multinomial coefficient of the
                // diagonal, and if the multinomial coefficient of any subset is zero, so is the
                // coefficient of the whole diagonal.
                let next_val = self.next_val(sum, self.M[i][j], max_inc + self.M[i][j]);
                let inc = next_val - self.M[i][j];

                // The remaining obstacle to incrementing this entry is the column sum condition.
                // For this, we only need a non-zero entry in the column j above row i.
                if inc <= max_inc {
                    // If so, we found our next matrix.
                    for row in 1..i {
                        self.M[row][0] = self.r.entry(row - 1);
                        for col in 1..self.cols {
                            self.M[0][col] += self.M[row][col];
                            self.M[row][col] = 0;
                        }
                    }
                    for col in 1..j {
                        self.M[0][col] += self.M[i][col];
                        self.M[i][col] = 0;
                    }
                    self.M[0][j] -= inc;
                    self.M[i][j] += inc;
                    self.M[i][0] = total - p_to_the_j * inc;
                    return true;
                }
                // All the cells above this one are zero so we didn't find our next matrix.
                // Add the weight from this cell to the total, we can use it to increment a cell lower down.
                total += self.M[i][j] * p_to_the_j;
            }
        }
        false
    }
}

impl<const MOD4: bool> Iterator for PPartMultiplier<MOD4> {
    type Item = u32;

    fn next(&mut self) -> Option<u32> {
        let p = self.prime().as_u32() as PPartEntry;
        'outer: loop {
            let mut coef = 1;

            if self.init {
                self.init = false;
                for i in 1..std::cmp::min(self.cols, self.rows) {
                    if MOD4 {
                        coef *= PPartEntry::binomial4(self.M[i][0] + self.M[0][i], self.M[0][i]);
                        coef %= 4;
                    } else {
                        coef *= PPartEntry::binomial(
                            self.prime(),
                            self.M[i][0] + self.M[0][i],
                            self.M[0][i],
                        );
                        coef %= p;
                    }
                    if coef == 0 {
                        continue 'outer;
                    }
                }
                // The answer is the top row of the matrix plus `r`, entrywise. Accumulate into
                // a plain word and store once; trailing zeros contribute nothing, so there is no
                // trimming to do.
                let mut ans = 0;
                for i in 0..std::cmp::max(self.cols, self.rows) - 1 {
                    let mut entry = self.r.entry(i);
                    if i + 1 < self.cols {
                        entry += self.M[0][i + 1];
                    }
                    debug_assert!(entry <= PPart::max_entry(i));
                    ans |= (entry as u64) << PPart::shift(i);
                }
                self.ans.p_part = PPart::from_bits(ans);
                return Some(coef);
            } else if self.update() {
                let mut ans = 0;
                for diag_idx in 1..=self.diag_num {
                    let i_min = (diag_idx + 1).saturating_sub(self.cols);
                    let i_max = std::cmp::min(diag_idx + 1, self.rows);
                    let mut sum = 0;

                    if self.prime() == 2 {
                        if MOD4 {
                            for i in i_min..i_max {
                                let entry = self.M[i][diag_idx - i];
                                sum += entry;
                                if coef.is_multiple_of(2) {
                                    coef *= PPartEntry::binomial2(sum, entry);
                                } else {
                                    coef *= PPartEntry::binomial4(sum, entry);
                                }
                                coef %= 4;
                                if coef == 0 {
                                    continue 'outer;
                                }
                            }
                        } else {
                            let mut or = 0;
                            for i in i_min..i_max {
                                sum += self.M[i][diag_idx - i];
                                or |= self.M[i][diag_idx - i];
                            }
                            if sum != or {
                                continue 'outer;
                            }
                        }
                    } else {
                        #[cfg(feature = "odd-primes")]
                        {
                            self.diagonal.clear();
                            for i in i_min..i_max {
                                self.diagonal.push(self.M[i][diag_idx - i]);
                                sum += self.M[i][diag_idx - i];
                            }

                            coef *= PPartEntry::multinomial_odd(self.prime(), &mut self.diagonal);
                            coef %= p;
                            if coef == 0 {
                                continue 'outer;
                            }
                        }
                    }
                    // `diag_num` counts diagonals of the working matrix, which can exceed the
                    // number of entries a p-part of this degree can have; those trailing
                    // diagonals are necessarily zero and need not be stored.
                    if diag_idx <= PPart::MAX_LEN {
                        debug_assert!(sum <= PPart::max_entry(diag_idx - 1));
                        ans |= (sum as u64) << PPart::shift(diag_idx - 1);
                    } else {
                        debug_assert_eq!(sum, 0);
                    }
                }
                self.ans.p_part = PPart::from_bits(ans);

                return Some(coef);
            } else {
                return None;
            }
        }
    }
}

impl MilnorAlgebra {
    fn decompose_basis_element_qpart(
        &self,
        degree: i32,
        idx: usize,
    ) -> Vec<(u32, (i32, usize), (i32, usize))> {
        let basis = self.basis_element_from_index(degree, idx);
        // Look for left-most non-zero qpart
        let i = basis.q_part.trailing_zeros();
        // If the basis element is just Q_{k+1}, we decompose Q_{k+1} = P(p^k) Q_k - Q_k P(p^k).
        if basis.q_part == 1 << i && basis.p_part.is_empty() {
            let ppow = self.prime().pow(i - 1);

            let q_degree = (2 * ppow - 1) as i32;
            let p_degree = (ppow * (2 * self.prime() - 2)) as i32;

            let p_idx = self
                .basis_element_to_index(&MilnorBasisElement::from_p(
                    PPart::from_iter([ppow as PPartEntry]),
                    p_degree,
                ))
                .to_owned();

            let q_idx = self
                .basis_element_to_index(&MilnorBasisElement {
                    q_part: 1 << (i - 1),
                    p_part: PPart::zero(),
                    degree: q_degree,
                })
                .to_owned();

            vec![
                (1, (p_degree, p_idx), (q_degree, q_idx)),
                (self.prime() - 1, (q_degree, q_idx), (p_degree, p_idx)),
            ]
        } else {
            // Otherwise, separate out the first Q_k.
            let first_degree = combinatorics::tau_degrees(self.prime())[i as usize];
            let second_degree = degree - first_degree;

            let first_idx = self.basis_element_to_index(&MilnorBasisElement {
                q_part: 1 << i,
                p_part: PPart::zero(),
                degree: first_degree,
            });

            let second_idx = self.basis_element_to_index(&MilnorBasisElement {
                q_part: basis.q_part ^ (1 << i),
                p_part: basis.p_part,
                degree: second_degree,
            });

            vec![(1, (first_degree, first_idx), (second_degree, second_idx))]
        }
    }

    fn decompose_basis_element_ppart(
        &self,
        degree: i32,
        idx: usize,
    ) -> Vec<(u32, (i32, usize), (i32, usize))> {
        let p = self.prime();

        // We define an ordering on the p parts as follows: we order each entry in reverse, and
        // then impose the reverse lexicographic ordering. Then for each non-generator P(R), `init`
        // is a partial decomposition such that the non-zero terms in the `init` product are all
        // greater than or equal to P(R) (and P(R) has non-zero coefficient in `init`). We can then
        // apply this algorithm recursively to decompose an element.

        // result is the products we have added so far
        let mut result = Vec::new();
        // buffer is the products we are adding in the current iteration
        let mut buffer = Vec::new();

        // out_vec is the remaining items we have to kill. We are done when this hits zero.
        let mut out_vec = FpVector::new(p, self.dimension(degree));
        out_vec.set_entry(idx, p - 1);

        while let Some((idx, c)) = out_vec.iter_nonzero().next() {
            let b = self.basis_element_from_index(degree, idx);
            let len = b.p_part.len();

            if b.p_part.truncate(len - 1).is_empty() {
                // There is only one entry
                let entry = b.p_part.get(len - 1);
                let (k, m) = factor_pk(p, entry);

                // This is a power of p
                if m == 1 {
                    if len == 1 || !self.profile.is_an(self.generic()) {
                        buffer.extend([(p - c, (degree, idx), (0, 0))]);
                    } else {
                        // Write this as [P(p^(len + k - 1)), P(0, .., 0, P^k)] plus higher order
                        // terms.
                        let l_entry = p.pow(len as u32 + k - 1) as PPartEntry;
                        let r_entry = p.pow(k) as PPartEntry;

                        let l_degree = l_entry as i32 * self.q();
                        let l_index = self.basis_element_to_index(&MilnorBasisElement {
                            q_part: 0,
                            p_part: PPart::from_iter([l_entry]),
                            degree: l_degree,
                        });

                        let mut r_p_part = PPart::zero();
                        r_p_part.set(len - 2, r_entry);
                        let r_degree =
                            r_entry as i32 * combinatorics::xi_degrees(p)[len - 2] * self.q();

                        let r_index = self.basis_element_to_index(&MilnorBasisElement {
                            q_part: 0,
                            p_part: r_p_part,
                            degree: r_degree,
                        });
                        buffer.extend(vec![
                            (p - c, (l_degree, l_index), (r_degree, r_index)),
                            (c, (r_degree, r_index), (l_degree, l_index)),
                        ])
                    }
                } else {
                    // This is not a power of p. Just subtract the lowest power of p.
                    let pk = p.pow(k) as PPartEntry;
                    let rem_entry = entry - pk;

                    let entry_deg = combinatorics::xi_degrees(p)[len - 1] * self.q();

                    let mut elt = MilnorBasisElement {
                        q_part: 0,
                        degree: 0,
                        p_part: PPart::zero(),
                    };

                    elt.p_part.set(len - 1, pk);
                    elt.degree = entry_deg * pk as i32;
                    let first = (elt.degree, self.basis_element_to_index(&elt));

                    elt.p_part.set(len - 1, rem_entry);
                    elt.degree = entry_deg * rem_entry as i32;
                    let second = (elt.degree, self.basis_element_to_index(&elt));

                    let coef =
                        p - fp::prime::inverse(p, PPartEntry::binomial(p, pk + rem_entry, pk));
                    buffer.extend([(coef, first, second)])
                }
            } else {
                // There is more than one entry. Just separate out the last entry.
                let last_entry = b.p_part.get(len - 1);
                let last_deg = combinatorics::xi_degrees(p)[len - 1] * self.q() * last_entry as i32;
                let mut elt = MilnorBasisElement {
                    q_part: 0,
                    p_part: PPart::zero(),
                    degree: last_deg,
                };
                elt.p_part.set(len - 1, last_entry);
                let first = (elt.degree, self.basis_element_to_index(&elt));

                elt.degree = degree - last_deg;
                elt.p_part = b.p_part.truncate(len - 1);
                let second = (elt.degree, self.basis_element_to_index(&elt));
                buffer.extend([(p - c, first, second)]);
            };
            for (c, first, second) in &buffer {
                self.multiply_basis_elements(
                    out_vec.as_slice_mut(),
                    *c,
                    first.0,
                    first.1,
                    second.0,
                    second.1,
                );
            }
            result.extend(&buffer);
            buffer.clear();
        }
        result
    }
}

impl MilnorAlgebra {
    /// Advance `element` to the next p-part bounded entrywise by `max`, in odometer order.
    ///
    /// Returns `true` once the odometer wraps, i.e. when `element` was already `max`.
    ///
    /// This carries *before* incrementing rather than after. The two orders enumerate the same
    /// sequence, but incrementing first would transiently store `max[i] + 1`, which need not fit
    /// in a packed field whose width is exactly saturated by `max[i]`.
    fn increment_p_part(element: &mut PPart, max: PPart) -> bool {
        for i in 0..max.len() {
            let entry = element.get(i);
            if entry < max.get(i) {
                element.set(i, entry + 1);
                return false;
            }
            element.set(i, 0);
        }
        true
    }
}

impl Bialgebra for MilnorAlgebra {
    fn coproduct(&self, op_deg: i32, op_idx: usize) -> Vec<(i32, usize, i32, usize)> {
        assert_eq!(self.prime(), 2, "Coproduct at odd primes not supported");
        if op_deg == 0 {
            return vec![(0, 0, 0, 0)];
        }
        let xi_degrees = combinatorics::xi_degrees(self.prime());

        let mut len = 1;
        let p_part = self.basis_element_from_index(op_deg, op_idx).p_part;

        for i in p_part.iter() {
            len *= i + 1;
        }
        let len = len as usize;
        let mut result = Vec::with_capacity(len);

        let n = p_part.len();
        let mut cur_ppart = PPart::zero();
        loop {
            let mut left_degree: i32 = 0;
            let mut right_ppart = PPart::zero();
            for (i, &xi_degree) in xi_degrees.iter().enumerate().take(n) {
                let entry = cur_ppart.get(i);
                left_degree += entry as i32 * xi_degree;
                // Trailing zeros are dropped by the packing, so no trimming is needed.
                right_ppart.set(i, p_part.get(i) - entry);
            }
            let right_degree: i32 = op_deg - left_degree;

            let left_idx = self.basis_element_to_index(&MilnorBasisElement {
                degree: left_degree,
                q_part: 0,
                p_part: cur_ppart,
            });
            let right_idx = self.basis_element_to_index(&MilnorBasisElement {
                degree: right_degree,
                q_part: 0,
                p_part: right_ppart,
            });

            result.push((left_degree, left_idx, right_degree, right_idx));
            if Self::increment_p_part(&mut cur_ppart, p_part) {
                break;
            }
        }
        result
    }

    fn decompose(&self, op_deg: i32, op_idx: usize) -> Vec<(i32, usize)> {
        vec![(op_deg, op_idx)]
    }
}

#[cfg(test)]
mod tests {
    use std::fmt::Write as _; // Needed for write! macro for String

    use expect_test::expect;
    use rstest::rstest;

    use super::*;

    #[rstest]
    #[trace]
    #[case(2, 32, None)]
    #[case(2, 32, Some(MilnorProfile { q_part: !0, p_part: vec!(3, 2, 1), truncated: true }))]
    #[case(2, 32, Some(MilnorProfile { q_part: !0, p_part: vec!(2, 2, 1), truncated: true }))]
    #[case(2, 32, Some(MilnorProfile { q_part: !0, p_part: vec!(0), truncated: false }))]
    #[case(3, 106, None)]
    #[case(3, 106, Some(MilnorProfile { q_part: 0b1111, p_part: vec!(3, 2, 1), truncated: true }))]
    #[case(3, 106, Some(MilnorProfile { q_part: 0b1111, p_part: vec!(2, 2, 1), truncated: true }))]
    fn test_milnor_decompose(
        #[case] p: u32,
        #[case] max_degree: i32,
        #[case] profile: Option<MilnorProfile>,
    ) {
        let p = ValidPrime::new(p);
        let algebra = MilnorAlgebra::new_with_profile(p, profile.unwrap_or_default(), false);
        algebra.compute_basis(max_degree);
        for i in 1..max_degree {
            let dim = algebra.dimension(i);
            let gens = algebra.generators(i);
            // println!("i : {}, gens : {:?}", i, gens);
            let mut out_vec = FpVector::new(p, dim);
            for j in 0..dim {
                if gens.contains(&j) {
                    continue;
                }
                for (coeff, (first_degree, first_idx), (second_degree, second_idx)) in
                    algebra.decompose_basis_element(i, j)
                {
                    // print!("{} * {} * {}  +  ", coeff, algebra.basis_element_to_string(first_degree,first_idx), algebra.basis_element_to_string(second_degree, second_idx));
                    algebra.multiply_basis_elements(
                        out_vec.as_slice_mut(),
                        coeff,
                        first_degree,
                        first_idx,
                        second_degree,
                        second_idx,
                    );
                }
                assert!(
                    out_vec.entry(j) == 1,
                    "{} != {}",
                    algebra.basis_element_to_string(i, j),
                    algebra.element_to_string(i, out_vec.as_slice())
                );
                out_vec.set_entry(j, 0);
                assert!(
                    out_vec.is_zero(),
                    "\n{} != {}",
                    algebra.basis_element_to_string(i, j),
                    algebra.element_to_string(i, out_vec.as_slice())
                );
            }
        }
    }

    #[rstest]
    #[trace]
    #[case(2, 32)]
    #[case(3, 106)]
    fn test_milnor_string(#[case] p: u32, #[case] max_degree: i32) {
        let p = ValidPrime::new(p);
        let algebra = MilnorAlgebra::new(p, false);
        algebra.compute_basis(max_degree);
        for t in 0..max_degree {
            for i in 0..algebra.dimension(t) {
                let elt = algebra.basis_element_to_string(t, i);
                assert_eq!(
                    Some((t, i)),
                    algebra.basis_element_from_string(&elt),
                    "Error parsing {elt}"
                );
            }
            for i in algebra.generators(t) {
                let elt = algebra.generator_to_string(t, i);
                assert_eq!(
                    Some((t, i)),
                    algebra.basis_element_from_string(&elt),
                    "Error parsing {elt}"
                );
            }
        }
    }

    #[test]
    fn try_beps_pn_milnor() {
        let p = ValidPrime::new(2);

        // On the full algebra, `try_beps_pn` agrees with the panicking `beps_pn`
        // for valid inputs and never returns `None` (every P(x), x >= 1, exists).
        let algebra = MilnorAlgebra::new(p, false);
        for x in 1..16 {
            assert_eq!(algebra.try_beps_pn(0, x), Some(algebra.beps_pn(0, x)));
            assert!(algebra.try_beps_pn(0, x).is_some());
        }

        // On A(2) (profile [3, 2, 1], truncated), the first xi exponent is bounded
        // by 2^3 - 1 = 7, so P(7) is present but P(8) is excluded by the profile.
        let a2 = MilnorAlgebra::new_with_profile(
            p,
            MilnorProfile {
                q_part: !0,
                p_part: vec![3, 2, 1],
                truncated: true,
            },
            false,
        );
        // Valid input: agrees with `beps_pn`.
        assert_eq!(a2.try_beps_pn(0, 7), Some(a2.beps_pn(0, 7)));
        // Invalid input: excluded by the profile, so `None` instead of a panic.
        assert_eq!(a2.try_beps_pn(0, 8), None);
    }

    /// `basis_element_from_string` is documented to be total. Inputs whose exponents overflow
    /// intermediate arithmetic must return `None`, not panic.
    #[test]
    fn basis_element_from_string_rejects_overflowing_exponents() {
        let algebra = MilnorAlgebra::new(fp::prime::TWO, false);
        algebra.compute_basis(8);

        // `t` indexes the xi-degree table, which has exactly `MAX_LEN` entries.
        assert_eq!(algebra.basis_element_from_string("P^1_10"), None);
        assert_eq!(algebra.basis_element_from_string("P^1_99"), None);
        // `p^s` overflows for large `s`.
        assert_eq!(algebra.basis_element_from_string("P^64_2"), None);
        assert_eq!(algebra.basis_element_from_string("P^4294967295_2"), None);
        // ... and so does `q * x` in the `Sq`/`P` path.
        assert_eq!(algebra.basis_element_from_string("Sq4294967295"), None);
    }

    /// `try_beps_pn` is the non-panicking half of `beps_pn`; an out-of-range `x` must not trip
    /// overflow on the way to the bounds check.
    #[test]
    fn try_beps_pn_rejects_overflowing_x() {
        for p in [2, 3] {
            let algebra = MilnorAlgebra::new(ValidPrime::new(p), false);
            assert_eq!(algebra.try_beps_pn(0, PPartEntry::MAX), None);
            assert_eq!(algebra.try_beps_pn(0, PPartEntry::MAX / 2), None);
            assert_eq!(algebra.try_beps_pn(1, PPartEntry::MAX), None);
        }
    }

    #[test]
    fn basis_element_from_string_total_milnor() {
        let p = ValidPrime::new(2);
        let algebra = MilnorAlgebra::new(p, false);
        algebra.compute_basis(8);

        // Sanity: valid names round-trip through the canonical string form.
        for name in ["P(1)", "P(2)", "P(0, 1)"] {
            let (d, i) = algebra
                .basis_element_from_string(name)
                .unwrap_or_else(|| panic!("expected Some for {name}"));
            assert_eq!(algebra.basis_element_to_string(d, i), name);
        }

        // "P0"/"Sq0" name the identity. A packed p-part does not represent trailing zeros, so
        // `P(0)` and `P()` are the same value, and `try_beps_pn(0, 0)` finds the degree-0 basis
        // element. This matches `AdemAlgebra::try_beps_pn`, which special-cases `x == 0` to
        // `Some((0, 0))`; the previous `None` here came from `vec![0]` and `vec![]` hashing
        // differently, which was an artifact of the unpacked representation.
        assert_eq!(algebra.basis_element_from_string("P0"), Some((0, 0)));
        assert_eq!(algebra.basis_element_from_string("Sq0"), Some((0, 0)));

        // Syntactically-valid names that name no basis element must still return `None`
        // (they previously panicked in `basis_element_to_index`).
        //
        // "Q_5" parses via the Q/P branch into a candidate element (degree 63)
        // whose basis lookup finds nothing at p = 2.
        assert_eq!(algebra.basis_element_from_string("Q_5"), None);

        // On A(2) (profile [3, 2, 1], truncated) the first xi exponent is bounded
        // by 2^3 - 1 = 7. "P7" exists; the out-of-profile "P8" parses to a valid
        // candidate that is excluded by the profile, so it must return `None`.
        let a2 = MilnorAlgebra::new_with_profile(
            p,
            MilnorProfile {
                q_part: !0,
                p_part: vec![3, 2, 1],
                truncated: true,
            },
            false,
        );
        a2.compute_basis(16);
        assert!(a2.basis_element_from_string("P7").is_some());
        assert_eq!(a2.basis_element_from_string("P8"), None);
    }

    use crate::module::ModuleFailedRelationError;
    #[rstest(p, max_degree, case(2, 32), case(3, 106))]
    #[trace]
    fn test_adem_relations(p: u32, max_degree: i32) {
        let p = ValidPrime::new(p);
        let algebra = MilnorAlgebra::new(p, false);
        algebra.compute_basis(max_degree + 2);
        let mut output_vec = FpVector::new(p, 0);
        for i in 1..max_degree {
            let output_dim = algebra.dimension(i);
            output_vec.set_scratch_vector_size(output_dim);
            let relations = algebra.generating_relations(i);
            println!("{relations:?}");
            for relation in relations {
                for (coeff, (deg_1, idx_1), (deg_2, idx_2)) in &relation {
                    algebra.multiply_basis_elements(
                        output_vec.as_slice_mut(),
                        *coeff,
                        *deg_1,
                        *idx_1,
                        *deg_2,
                        *idx_2,
                    );
                }
                if !output_vec.is_zero() {
                    let mut relation_string = String::new();
                    for (coeff, (deg_1, idx_1), (deg_2, idx_2)) in &relation {
                        let _ = write!(
                            relation_string,
                            "{} * {} * {}  +  ",
                            coeff,
                            algebra.basis_element_to_string(*deg_1, *idx_1),
                            algebra.basis_element_to_string(*deg_2, *idx_2)
                        );
                    }
                    relation_string.pop();
                    relation_string.pop();
                    relation_string.pop();
                    relation_string.pop();
                    relation_string.pop();
                    let value_string = algebra.element_to_string(i, output_vec.as_slice());
                    panic!(
                        "{}",
                        ModuleFailedRelationError {
                            relation: relation_string,
                            value: value_string
                        }
                    );
                }
            }
        }
    }

    /// The packing is only sound because each field is wide enough for every entry that can occur
    /// at degree at most `MAX_DEGREE`. Check that against the $\xi$-degrees directly, so that
    /// changing `MAX_DEGREE` or `WIDTHS` without the other fails loudly.
    #[test]
    fn ppart_widths_cover_max_degree() {
        let xi_degrees = combinatorics::xi_degrees(fp::prime::TWO);
        for (i, &xi_degree) in xi_degrees.iter().enumerate().take(PPart::MAX_LEN) {
            // deg P(R) = sum_i r_i (2^i - 1) with non-negative terms, so r_i <= deg / (2^i - 1).
            let bound = PPart::MAX_DEGREE / xi_degree;
            assert!(
                bound <= PPart::max_entry(i) as i32,
                "entry {i} needs to hold {bound} but only holds up to {}",
                PPart::max_entry(i),
            );
        }
        // There is no entry beyond `MAX_LEN` to store: the xi-degree table itself stops there, so
        // `compute_ppart` cannot produce a longer p-part. If `fp` ever raises
        // `MAX_MULTINOMIAL_LEN`, this fires and `WIDTHS` has to be revisited.
        assert_eq!(xi_degrees.len(), PPart::MAX_LEN);
        // ... and the layout uses the whole word, so `MAX_DEGREE` is as large as it can be.
        assert_eq!(
            PPart::shift(PPart::MAX_LEN - 1) + PPart::width(PPart::MAX_LEN - 1),
            64
        );
    }

    #[test]
    fn ppart_accessors() {
        let mut p = PPart::from_slice(&[3, 0, 5]);
        assert_eq!(p.len(), 3);
        assert_eq!(p.iter().collect::<Vec<_>>(), vec![3, 0, 5]);
        assert_eq!(p.get(1), 0);
        assert_eq!(p.get(2), 5);
        // Reading past the end is zero, not a panic.
        assert_eq!(p.get(7), 0);
        assert_eq!(p.get(PPart::MAX_LEN), 0);

        // Trailing zeros are not represented, so they do not affect equality, length or hashing.
        assert_eq!(PPart::from_slice(&[3, 0, 5, 0, 0]), p);
        assert_eq!(PPart::from_slice(&[]), PPart::zero());
        assert_eq!(PPart::from_slice(&[0, 0]), PPart::zero());
        assert_eq!(PPart::zero().len(), 0);
        assert!(PPart::zero().is_empty());

        assert_eq!(p.truncate(2), PPart::from_slice(&[3]));
        assert_eq!(p.truncate(0), PPart::zero());
        assert_eq!(p.truncate(PPart::MAX_LEN + 3), p);

        p.set(1, 7);
        assert_eq!(p, PPart::from_slice(&[3, 7, 5]));
        p.set(2, 0);
        assert_eq!(p, PPart::from_slice(&[3, 7]));
    }

    #[test]
    fn ppart_rejects_out_of_range() {
        // Too many entries, and an entry too large for its field.
        assert_eq!(PPart::try_from_slice(&[1; PPart::MAX_LEN + 1]), None);
        assert_eq!(PPart::try_from_slice(&[0, PPart::max_entry(1) + 1]), None);
        // ... but a zero past the end is only padding.
        let mut padded = vec![0; PPart::MAX_LEN + 4];
        padded[0] = 2;
        assert_eq!(
            PPart::try_from_slice(&padded),
            Some(PPart::from_slice(&[2]))
        );
    }

    #[test]
    #[should_panic(expected = "does not fit")]
    fn ppart_set_out_of_range_panics() {
        PPart::zero().set(0, PPart::max_entry(0) + 1);
    }

    /// `increment_p_part` walks up to and including `max`, whose top entry may saturate its field.
    /// Incrementing before carrying would overflow there.
    #[test]
    fn ppart_odometer_handles_saturated_field() {
        let top = PPart::MAX_LEN - 1;
        let mut max = PPart::from_slice(&[2]);
        max.set(top, PPart::max_entry(top));

        let mut count = 0;
        let mut cur = PPart::zero();
        loop {
            count += 1;
            if MilnorAlgebra::increment_p_part(&mut cur, max) {
                break;
            }
        }
        assert_eq!(count, 3 * (PPart::max_entry(top) as usize + 1));
        // Wrapping leaves the odometer back at zero.
        assert_eq!(cur, PPart::zero());
    }

    /// Pack every basis element the algebra actually produces and check nothing collides or is
    /// lost. This is the property the whole representation rests on.
    #[rstest]
    #[case(2, 120)]
    #[case(3, 200)]
    fn ppart_packing_is_faithful(#[case] p: u32, #[case] max_degree: i32) {
        let algebra = MilnorAlgebra::new(ValidPrime::new(p), false);
        algebra.compute_basis(max_degree);

        for t in 0..=max_degree {
            let mut seen = HashMap::default();
            for i in 0..algebra.dimension(t) {
                let elt = algebra.basis_element_from_index(t, i);
                // The packed value plus the q-part identifies the element within its degree.
                assert!(
                    seen.insert((elt.p_part.bits(), elt.q_part), i).is_none(),
                    "collision at degree {t} for {elt}"
                );
                // Round-trip through a slice, and back through the index map.
                assert_eq!(
                    PPart::from_slice(&elt.p_part.iter().collect::<Vec<_>>()),
                    elt.p_part
                );
                assert_eq!(algebra.basis_element_to_index(&elt), i);
                // The degree really is recoverable from the entries.
                let mut recomputed = elt;
                recomputed.compute_degree(ValidPrime::new(p));
                assert_eq!(recomputed.degree, t);
            }
        }
    }

    /// The basis *order* at `p = 2` is a wire format: saved resolutions store coefficients by
    /// index, so reordering silently invalidates them without `magic()` changing. Deriving the
    /// basis from `ppart_table` preserves the order `generate_basis_2` produced, since the stable
    /// path never sorted. Pin that down against fixed expected names, so the check does not depend
    /// on `ppart_table` -- the very thing it is guarding.
    #[test]
    fn basis_order_at_p2_is_stable() {
        let algebra = MilnorAlgebra::new(fp::prime::TWO, false);
        algebra.compute_basis(8);

        let expected: [&[&str]; 9] = [
            &["1"],
            &["P(1)"],
            &["P(2)"],
            &["P(3)", "P(0, 1)"],
            &["P(4)", "P(1, 1)"],
            &["P(5)", "P(2, 1)"],
            &["P(6)", "P(3, 1)", "P(0, 2)"],
            &["P(7)", "P(4, 1)", "P(1, 2)", "P(0, 0, 1)"],
            &["P(8)", "P(5, 1)", "P(2, 2)", "P(1, 0, 1)"],
        ];
        for (t, names) in expected.iter().enumerate() {
            let t = t as i32;
            assert_eq!(algebra.dimension(t), names.len(), "dimension in degree {t}");
            for (i, name) in names.iter().enumerate() {
                assert_eq!(
                    &algebra.basis_element_to_string(t, i),
                    name,
                    "degree {t}, index {i}"
                );
            }
        }
    }

    /// At `p = 2` with unstable support off, the basis is not stored: it is derived from
    /// `ppart_table`. Check the derivation reproduces exactly what the table used to hold, so the
    /// redundancy this relies on is asserted rather than assumed.
    #[test]
    fn basis_is_derived_at_p2() {
        let p = fp::prime::TWO;
        let algebra = MilnorAlgebra::new(p, false);
        algebra.compute_basis(120);
        assert!(
            !algebra.stores_basis_table(),
            "p = 2 stable should not be storing the basis"
        );

        for t in 0..=120 {
            let pparts = algebra.ppart_table(t);
            assert_eq!(algebra.dimension(t), pparts.len());
            for (i, &p_part) in pparts.iter().enumerate() {
                // This is precisely what `generate_basis_2` used to store.
                let expected = MilnorBasisElement {
                    q_part: 0,
                    p_part,
                    degree: t,
                };
                let actual = algebra.basis_element_from_index(t, i);
                assert_eq!(actual.p_part, expected.p_part, "degree {t}, index {i}");
                assert_eq!(actual.q_part, expected.q_part, "degree {t}, index {i}");
                assert_eq!(actual.degree, expected.degree, "degree {t}, index {i}");
            }
        }
    }

    /// The two configurations that still need the table really do differ from `ppart_table`, so
    /// the exemption in `stores_basis_table` is not over-broad.
    #[rstest]
    #[case(3, false)]
    #[case(2, true)]
    fn basis_is_stored_when_it_must_be(#[case] p: u32, #[case] unstable: bool) {
        let algebra = MilnorAlgebra::new(ValidPrime::new(p), unstable);
        algebra.compute_basis(60);
        assert!(algebra.stores_basis_table());
        // Every stored element still round-trips through the index map.
        for t in 0..=60 {
            for i in 0..algebra.dimension(t) {
                let elt = algebra.basis_element_from_index(t, i);
                assert_eq!(algebra.basis_element_to_index(&elt), i);
            }
        }
    }

    #[test]
    fn test_clone_into() {
        let mut other = MilnorBasisElement::default();

        let mut check = |a: &MilnorBasisElement| {
            a.clone_into(&mut other);
            assert_eq!(a, &other);
        };

        check(&MilnorBasisElement {
            q_part: 3,
            p_part: PPart::from_slice(&[3, 2]),
            degree: 12,
        });
        check(&MilnorBasisElement {
            q_part: 1,
            p_part: PPart::from_slice(&[3]),
            degree: 11,
        });
        check(&MilnorBasisElement {
            q_part: 5,
            p_part: PPart::from_slice(&[1, 3, 5, 2]),
            degree: 7,
        });
        check(&MilnorBasisElement {
            q_part: 0,
            p_part: PPart::zero(),
            degree: 2,
        });
    }

    #[test]
    fn test_ppart_multiplier_2() {
        let r = PPart::from_slice(&[1, 4]);
        let s = PPart::from_slice(&[2, 4]);
        let mut m = PPartMultiplier::<false>::new_from_allocation(
            fp::prime::TWO,
            r,
            s,
            PPartAllocation::default(),
            0,
            0,
        );

        expect![[r#"
            [0, 2, 4]
            [1, 0, 0]
            [4, 0, 0]
        "#]]
        .assert_eq(&m.M.to_string());

        assert_eq!(m.next(), Some(1));

        expect![[r#"
            [0, 0, 4]
            [1, 0, 0]
            [0, 2, 0]
        "#]]
        .assert_eq(&m.M.to_string());

        assert_eq!(m.next(), Some(1));

        expect![[r#"
            [0, 2, 3]
            [1, 0, 0]
            [0, 0, 1]
        "#]]
        .assert_eq(&m.M.to_string());

        assert_eq!(m.next(), None);
    }

    #[test]
    fn test_ppart_multiplier_3() {
        let r = PPart::from_slice(&[3, 4]);
        let s = PPart::from_slice(&[1, 4]);
        let mut m = PPartMultiplier::<false>::new_from_allocation(
            ValidPrime::new(3),
            r,
            s,
            PPartAllocation::default(),
            0,
            0,
        );

        expect![[r#"
            [0, 1, 4]
            [3, 0, 0]
            [4, 0, 0]
        "#]]
        .assert_eq(&m.M.to_string());

        assert_eq!(m.next(), Some(1));

        expect![[r#"
            [0, 1, 4]
            [3, 0, 0]
            [4, 0, 0]
        "#]]
        .assert_eq(&m.M.to_string());

        assert_eq!(m.next(), Some(2));

        expect![[r#"
            [0, 0, 4]
            [3, 0, 0]
            [1, 1, 0]
        "#]]
        .assert_eq(&m.M.to_string());

        assert_eq!(m.next(), None);
    }

    #[test]
    fn test_valid_profile() {
        assert!(
            (MilnorProfile {
                p_part: vec![3, 2, 1],
                q_part: !0,
                truncated: true
            })
            .is_valid()
        );

        assert!(
            !(MilnorProfile {
                p_part: vec![3, 2],
                q_part: !0,
                truncated: true
            })
            .is_valid()
        );

        assert!(
            (MilnorProfile {
                p_part: vec![3, 2, 1],
                q_part: 0b1111,
                truncated: true
            })
            .is_valid()
        );

        assert!(
            (MilnorProfile {
                p_part: vec![2, 4, 2],
                q_part: 0,
                truncated: false
            })
            .is_valid()
        );

        assert!(
            !(MilnorProfile {
                p_part: vec![3, 2, 1],
                q_part: 0b111,
                truncated: true
            })
            .is_valid()
        );
    }
}
