use std::cmp::{min, max};
use std::sync::{Arc, Weak, RwLock, Mutex};
use std::collections::HashSet;

use bivec::BiVec;

use crate::fp_vector::{FpVector, FpVectorT};
use crate::matrix::{Matrix, Subspace};
use crate::algebra::{Algebra, AlgebraAny};
use crate::module::{Module, FiniteModule, FDModule, FreeModule};
use once::{OnceVec, OnceBiVec};
use crate::module::homomorphism::{ModuleHomomorphism, FreeModuleHomomorphism};
use crate::chain_complex::{ChainComplex, AugmentedChainComplex, FiniteChainComplex};
use crate::resolution_homomorphism::{ResolutionHomomorphism, ResolutionHomomorphismToUnit};
use crate::CCC;

#[cfg(feature = "concurrent")]
use rayon::prelude::*;

/// ResolutionInner contains the data of the actual resolution, while Resolution contains the bells
/// and whistles such as self maps and callbacks. ResolutionInner is what ResolutionHomomorphism
/// needs to take in, and is always an immutable object, so is wrapped in Arc<> instead of
/// Arc<RwLock>.

/// This separation should make multithreading easier because we only need ResolutionInner to be
/// Send + Sync. In particular, we don't need the callback functions to be Send + Sync.
pub struct ResolutionInner<CC : ChainComplex> {
    complex : Arc<CC>,
    modules : OnceVec<Arc<FreeModule>>,
    zero_module : Arc<FreeModule>,
    chain_maps : OnceVec<Arc<FreeModuleHomomorphism<CC::Module>>>,
    differentials : OnceVec<Arc<FreeModuleHomomorphism<FreeModule>>>,
    kernels : OnceBiVec<Mutex<Option<Subspace>>>
}

impl<CC : ChainComplex> ResolutionInner<CC> {
    pub fn new(complex : Arc<CC>) -> Self {
        let algebra = complex.algebra();
        let min_degree = complex.min_degree();
        let zero_module = Arc::new(FreeModule::new(Arc::clone(&algebra), "F_{-1}".to_string(), min_degree));

        Self {
            complex,
            zero_module,

            chain_maps : OnceVec::new(),
            modules : OnceVec::new(),
            differentials : OnceVec::new(),
            kernels : OnceBiVec::new(min_degree)
        }
    }

    /// This function prepares the ResolutionInner object to perform computations up to the
    /// specified s degree. It does *not* perform any computations by itself. It simply lengthens
    /// the `OnceVec`s `modules`, `chain_maps`, etc. to the right length.
    fn extend_through_degree(&self, mut next_s : u32, max_s : u32, next_t : i32, max_t : i32) {
        let min_degree = self.min_degree();

        for i in next_s ..= max_s {
            self.modules.push(Arc::new(FreeModule::new(Arc::clone(&self.algebra()), format!("F{}", i), min_degree)));
            self.chain_maps.push(Arc::new(FreeModuleHomomorphism::new(Arc::clone(&self.modules[i]), Arc::clone(&self.complex.module(i)), 0)));
        }

        for _ in next_t ..= max_t {
            self.kernels.push(Mutex::new(None));
        }

        if next_s == 0 {
            self.differentials.push(Arc::new(FreeModuleHomomorphism::new(Arc::clone(&self.modules[0u32]), Arc::clone(&self.zero_module), 0)));
            next_s += 1;
        }
        for i in next_s ..= max_s {
            self.differentials.push(Arc::new(FreeModuleHomomorphism::new(Arc::clone(&self.modules[i]), Arc::clone(&self.modules[i - 1]), 0)));
        }
    }

    /// Call our resolution $X$, and the chain complex to resolve $C$. This is a legitimate
    /// resolution if the map $f: X \to C$ induces an isomorphism on homology. This is the same as
    /// saying the cofiber is exact. The cofiber is given by the complex
    ///
    /// $$ X_s \oplus C_{s+1} \to X_{s-1} \oplus C_s \to X_{s-2} \oplus C_{s-1} \to \cdots $$
    ///
    /// where the differentials are given by
    ///
    /// $$ \begin{pmatrix} d_X & 0 \\\\ (-1)^s f & d_C \end{pmatrix} $$
    ///
    /// Our method of producing $X_{s, t}$ and the chain maps are as follows. Suppose we have already
    /// built the chain map and differential for $X_{s-1, t}$ and $X_{s, t-1}$. Since $X_s$ is a
    /// free module, the generators in degree $< t$ gives us a bunch of elements in $X_s$ already,
    /// and we know exactly where they get mapped to. Let $T$ be the $\\mathbb{F}_p$ vector space
    /// generated by these elements. Then we already have a map
    ///
    /// $$ T \to X_{s-1, t} \oplus C_{s, t}$$
    ///
    /// and we know this hits the kernel of the map
    ///
    /// $$ D = X_{s-1, t} \oplus C_{s, t} \to X_{s-2, t} \oplus C_{s-1, t}. $$
    ///
    /// What we need to do now is to add generators to $X_{s, t}$ to hit the entirity of this
    /// kernel.  Note that we don't *have* to do this. Some of the elements in the kernel might be
    /// hit by $C_{s+1, t}$ and we don't have to hit them, but we opt to add generators to hit it
    /// anyway.
    ///
    /// If we do it this way, then we know the composite of the map
    ///
    /// $$ T \to X_{s-1, t} \oplus C_{s, t} \to C_{s, t} $$
    ///
    /// has to be surjective, since the image of $C_{s, t}$ under $D$ is also in the image of $X_{s-1, t}$.
    /// So our first step is to add generators to $X_{s, t}$ such that this composite is
    /// surjective.
    ///
    /// After adding these generators, we need to decide where to send them to. We know their
    /// values in the $C_{s, t}$ component, but we need to use a quasi-inverse to find the element in
    /// $X_{s-1, t}$ that hits the corresponding image of $C_{s, t}$. This tells us the $X_{s-1,
    /// t}$ component.
    ///
    /// Finally, we need to add further generators to $X_{s, t}$ to hit all the elements in the
    /// kernel of
    ///
    /// $$ X_{s-1, t} \to X_{s-2, t} \oplus C_{s-1, t}. $$
    ///
    /// This kernel was recorded by the previous iteration of the method in `old_kernel`, so this
    /// step is doable as well.
    ///
    /// Note that if we add our new generators conservatively, then the kernel of the maps
    ///
    /// $$
    /// \begin{aligned}
    /// T &\to X_{s-1, t} \oplus C_{s, t} \\\\
    /// X_{s, t} &\to X_{s-1, t} \oplus C_{s, t}
    /// \end{aligned}
    /// $$
    /// agree.
    ///
    /// In the code, we first row reduce the matrix of the map from $T$. This lets us record
    /// the kernel which is what the function returns at the end. This computation helps us perform
    /// the future steps since we need to know about the cokernel of this map.
    ///
    /// # Arguments
    ///  * `s` - The s degree to calculate
    ///  * `t` - The t degree to calculate
    pub fn step_resolution(&self, s : u32, t : i32) {
        if s == 0 {
            self.zero_module.extend_by_zero(t);
        }

        let mut old_kernel = self.kernels[t].lock().unwrap();
        let p = self.prime();

        //                           current_chain_map
        //                X_{s, t} --------------------> C_{s, t}
        //                   |                               |
        //                   | current_differential          |
        //                   v                               v
        // old_kernel <= X_{s-1, t} -------------------> C_{s-1, t}

        let current_differential = self.differential(s);
        let current_chain_map = self.chain_map(s);

        let complex = self.complex();
        let complex_cur_differential = complex.differential(s);
        let source = &current_differential.source();
        let target_cc = &current_chain_map.target();
        target_cc.compute_basis(t);
        let target_res = &current_differential.target();
        let (source_lock, source_module_table) = source.construct_table(t);
        let mut chain_map_lock = current_chain_map.lock();
        let mut differential_lock = current_differential.lock();
        let source_dimension = FreeModule::dimension_with_table(&source_module_table);
        let target_cc_dimension = target_cc.dimension(t);
        let target_res_dimension = target_res.dimension(t);
        let target_dimension = target_cc_dimension + target_res_dimension;
        // The Homomorphism matrix has size source_dimension x target_dimension, but we are going to augment it with an
        // identity matrix so that gives a matrix with dimensions source_dimension x (target_dimension + source_dimension).
        // Later we're going to write into this same matrix an isomorphism source/image + new vectors --> kernel
        // This has size target_dimension x (2*target_dimension).
        // This latter matrix may be used to find a preimage of an element under the differential.

        // Pad the target dimension so that it ends in an aligned position.
        let padded_target_cc_dimension = FpVector::padded_dimension(p, target_cc_dimension);
        let padded_target_res_dimension = FpVector::padded_dimension(p, target_res_dimension);
        let padded_target_dimension = padded_target_res_dimension + padded_target_cc_dimension;
        let rows = source_dimension + target_dimension;
        let columns = padded_target_dimension + source_dimension + rows;
        let mut matrix = Matrix::new(p, rows, columns);
        let mut pivots = vec![-1;matrix.columns()];
        matrix.set_slice(0, source_dimension, 0, padded_target_dimension + source_dimension);
        // Get the map (d, f) : X_{s, t} -> X_{s-1, t} (+) C_{s, t} into matrix
        current_chain_map.get_matrix_with_table(&mut matrix, &source_module_table, t, 0, 0);
        current_differential.get_matrix_with_table(&mut matrix, &source_module_table, t, 0, padded_target_cc_dimension);
        // Augment with the identity matrix.
        matrix.set_identity(source_dimension, 0, padded_target_dimension);
        matrix.row_reduce(&mut pivots);

        let new_kernel = matrix.compute_kernel(&pivots, padded_target_dimension);
        let first_new_row = source_dimension;
        matrix.clear_slice();

        // Now add generators to surject onto C_{s, t}.
        // (For now we are just adding the eventual images of the new generators into matrix, we will update
        // X_{s,t} and f later).
        // We record which pivots exactly we added so that we can walk over the added genrators in a moment and
        // work out what dX should to to each of them.
        let new_generators = matrix.extend_to_surjection(first_new_row, 0, target_cc_dimension, &pivots);
        let cc_new_gens = new_generators.len();
        let mut res_new_gens = 0;

        let mut middle_rows = Vec::with_capacity(cc_new_gens);
        if s > 0 {
            if cc_new_gens > 0 {
                // Now we need to make sure that we have a chain homomorphism. Each generator x we just added to 
                // X_{s,t} has a nontrivial image f(x) \in C_{s,t}. We need to set d(x) so that f(dX(x)) = dC(f(x)).
                // So we set dX(x) = f^{-1}(dC(f(x)))
                let prev_chain_map = self.chain_map(s - 1);
                let quasi_inverse = prev_chain_map.quasi_inverse(t);

                let mut out_vec = FpVector::new(self.prime(), target_res_dimension);
                let dfx_dim = complex_cur_differential.target().dimension(t);
                let mut dfx = FpVector::new(self.prime(), dfx_dim);
                for (i, column) in new_generators.into_iter().enumerate() {
                    complex_cur_differential.apply_to_basis_element(&mut dfx, 1, t, column);
                    quasi_inverse.apply(&mut out_vec, 1, &dfx);
                    // Now out_vec contains f^{-1}(dC(f(x))).
                    let out_row = &mut matrix[first_new_row + i];
                    // dX(x) goes into the column range [padded_target_cc_dimension, padded_target_cc_dimension + target_res_dimension] in the matrix
                    // I think we are missing a sign here.
                    out_row.set_slice(padded_target_cc_dimension, padded_target_cc_dimension + target_res_dimension);
                    out_row.assign(&out_vec);
                    out_row.clear_slice();
                    dfx.set_to_zero();
                    out_vec.set_to_zero();

                    // Keep the rows we produced because we have to row reduce to re-compute
                    // the kernel later, but these rows are the images of the generators, so we
                    // still need them.
                    middle_rows.push(out_row.clone());
                }
                // Row reduce again since our activity may have changed the image of dX.
                matrix.row_reduce(&mut pivots);
            }
            // Now we add new generators to hit any cycles in old_kernel that we don't want in our homology.
             res_new_gens = matrix.extend_image(first_new_row + cc_new_gens, padded_target_cc_dimension, padded_target_cc_dimension + target_res_dimension, &pivots, &old_kernel).len();
        }
        let num_new_gens = cc_new_gens + res_new_gens;
        source.add_generators(t, source_lock, source_module_table, num_new_gens, None);

        for (i, row) in middle_rows.into_iter().enumerate() {
            matrix[first_new_row + i] = row;
        }
        current_chain_map.add_generators_from_matrix_rows(&chain_map_lock, t, &mut matrix, first_new_row, 0);
        current_differential.add_generators_from_matrix_rows(&differential_lock, t, &mut matrix, first_new_row, padded_target_cc_dimension);

        // Record the quasi-inverses for future use.
        // The part of the matrix that contains interesting information is occupied_rows x (target_dimension + source_dimension + kernel_size).
        let image_rows = first_new_row + num_new_gens;
        for i in first_new_row .. image_rows {
            matrix[i].set_entry(padded_target_dimension + i, 1);
        }
        matrix.set_slice(0, image_rows, 0, padded_target_dimension + source_dimension + num_new_gens); 
        let mut new_pivots = vec![-1;matrix.columns()];
        matrix.row_reduce(&mut new_pivots);
        let (cm_qi, res_qi) = matrix.compute_quasi_inverses(
            &new_pivots, 
            padded_target_cc_dimension, 
            padded_target_cc_dimension + target_res_dimension,
            padded_target_dimension
        );

        current_chain_map.set_quasi_inverse(&chain_map_lock, t, cm_qi);
        current_chain_map.set_kernel(&chain_map_lock, t, Subspace::new(p, 0, 0)); // Fill it up with something dummy so that compute_kernels_and... is happy
        current_differential.set_quasi_inverse(&differential_lock, t, res_qi);
        current_differential.set_kernel(&differential_lock, t, Subspace::new(p, 0, 0));
        *chain_map_lock += 1;
        *differential_lock += 1;

        *old_kernel = Some(new_kernel);
    }

    pub fn cocycle_string(&self, hom_deg : u32, int_deg : i32, idx : usize) -> String {
        let p = self.prime();
        let d = self.differential(hom_deg);
        let source = self.module(hom_deg);
        let target = d.target();
        let dimension = target.dimension(int_deg);
        let basis_idx = source.operation_generator_to_index(0, 0, int_deg, idx);
        let mut result_vector = crate::fp_vector::FpVector::new(p, dimension);
        d.apply_to_basis_element(&mut result_vector, 1, int_deg, basis_idx);
        return target.element_to_string(int_deg, &result_vector);
    }

    pub fn complex(&self) -> Arc<CC> {
        Arc::clone(&self.complex)
    }

    pub fn number_of_gens_in_bidegree(&self, homological_degree : u32, internal_degree : i32) -> usize {
        self.module(homological_degree).number_of_gens_in_degree(internal_degree)
    }

    pub fn prime(&self) -> u32 {
        self.complex.prime()
    }
}

impl<CC : ChainComplex> ChainComplex for ResolutionInner<CC>
{
    type Module = FreeModule;
    type Homomorphism = FreeModuleHomomorphism<FreeModule>;

    fn algebra(&self) -> Arc<AlgebraAny> {
        self.complex().algebra()
    }

    fn module(&self, homological_degree : u32) -> Arc<Self::Module> {
        Arc::clone(&self.modules[homological_degree as usize])
    }

    fn zero_module(&self) -> Arc<Self::Module> {
        Arc::clone(&self.zero_module)
    }

    fn min_degree(&self) -> i32 {
        self.complex().min_degree()
    }

    fn set_homology_basis(&self, homological_degree : u32, internal_degree : i32, homology_basis : Vec<usize>){
        unimplemented!()
    }

    fn homology_basis(&self, homological_degree : u32, internal_degree : i32) -> &Vec<usize>{
        unimplemented!()
    }

    fn homology_dimension(&self, homological_degree : u32, internal_degree : i32) -> usize {
        self.number_of_gens_in_bidegree(homological_degree, internal_degree)
    }

    fn max_homology_degree(&self, homological_degree : u32) -> i32 {
        unimplemented!()
    }

    fn differential(&self, s : u32) -> Arc<Self::Homomorphism> {
        Arc::clone(&self.differentials[s as usize])
    }

    fn compute_through_bidegree(&self, s : u32, t : i32) {
        assert!(self.modules.len() > s as usize);
        assert!(self.modules[0 as usize].max_computed_degree() >= t);
    }
}

impl<CC : ChainComplex> AugmentedChainComplex for ResolutionInner<CC> {
    type TargetComplex = CC;
    type ChainMap = FreeModuleHomomorphism<CC::Module>;

    fn target(&self) -> Arc<Self::TargetComplex> {
        self.complex()
    }

    fn chain_map(&self, s : u32) -> Arc<Self::ChainMap> {
        Arc::clone(&self.chain_maps[s])
    }
}

/// Hack to compare two pointers of different types (in this case because they might have different
/// type parameters.
fn ptr_eq<T, S>(a : &Arc<T>, b : &Arc<S>) -> bool {
    let a = Arc::into_raw(Arc::clone(a));
    let b = Arc::into_raw(Arc::clone(b)) as *const T;
    let eq = std::ptr::eq(a, b);
    unsafe {
        let _ = Arc::from_raw(a);
        let _ = Arc::from_raw(b as *const S);
    }
    eq
}

#[derive(Clone)]
struct Cocycle {
    s : u32,
    t : i32,
    class : Vec<u32>,
    name : String
}

pub struct SelfMap<CC : ChainComplex> {
    pub s : u32,
    pub t : i32,
    pub name : String,
    pub map_data : Matrix,
    pub map : ResolutionHomomorphism<CC, ResolutionInner<CC>>
}

/// # Fields
///  * `kernels` - For each *internal* degree, store the kernel of the most recently calculated
///  chain map as returned by `generate_old_kernel_and_compute_new_kernel`, to be used if we run
///  resolve_through_degree again.
pub struct Resolution<CC : ChainComplex> {
    pub inner : Arc<ResolutionInner<CC>>,

    next_s : Mutex<u32>,
    next_t : Mutex<i32>,
    pub add_class : Option<Box<dyn Fn(u32, i32, usize)>>,
    pub add_structline : Option<Box<dyn Fn(
        &str,
        u32, i32,
        u32, i32,
        bool,
        Vec<Vec<u32>>
    )>>,

    filtration_one_products : Vec<(String, i32, usize)>,

    // Products
    pub unit_resolution : Option<Weak<RwLock<Resolution<CCC>>>>,
    pub unit_resolution_owner : Option<Arc<RwLock<Resolution<CCC>>>>,
    product_names : HashSet<String>,
    product_list : Vec<Cocycle>,
    // s -> t -> idx -> resolution homomorphism to unit resolution. We don't populate this
    // until we actually have a unit resolution, of course.
    chain_maps_to_unit_resolution : OnceVec<OnceBiVec<OnceVec<ResolutionHomomorphismToUnit<CC>>>>,
    max_product_homological_degree : u32,

    // Self maps
    pub self_maps : Vec<SelfMap<CC>>
}

impl<CC : ChainComplex> Resolution<CC> {
    pub fn new(
        complex : Arc<CC>,
        add_class : Option<Box<dyn Fn(u32, i32, usize)>>,
        add_structline : Option<Box<dyn Fn(
            &str,
            u32, i32,
            u32, i32,
            bool,
            Vec<Vec<u32>>
        )>>
    ) -> Self {
        let inner = Arc::new(ResolutionInner::new(complex));
        let min_degree = inner.min_degree();
        let algebra = inner.complex().algebra();

        Self {
            inner,

            next_s : Mutex::new(0),
            next_t : Mutex::new(min_degree),
            add_class,
            add_structline,

            filtration_one_products : algebra.default_filtration_one_products(),

            chain_maps_to_unit_resolution : OnceVec::new(),
            max_product_homological_degree : 0,
            product_names : HashSet::new(),
            product_list : Vec::new(),
            unit_resolution : None,
            unit_resolution_owner : None,

            self_maps : Vec::new()
        }
    }

    pub fn resolve_through_bidegree(&self, mut max_s : u32, mut max_t : i32) {
        let min_degree = self.min_degree();
        let mut next_s = self.next_s.lock().unwrap();
        let mut next_t = self.next_t.lock().unwrap();

        // We want the computed area to always be a rectangle.
        max_t = max(max_t, *next_t - 1);
        if max_s < *next_s {
            max_s = *next_s - 1;
        }

        self.inner.extend_through_degree(*next_s, max_s, *next_t, max_t);
        self.algebra().compute_basis(max_t - min_degree);

        for t in min_degree ..= max_t {
            if let Some(unit_res) = &self.unit_resolution {
                let unit_res = unit_res.upgrade().unwrap();
                let unit_res = unit_res.read().unwrap();
                // Avoid a deadlock
                if !ptr_eq(&unit_res.inner, &self.inner) {
                    unit_res.resolve_through_bidegree(self.max_product_homological_degree, t - min_degree);
                }
            }

            let start = if t < *next_t { *next_s } else { 0 };
            for s in start ..= max_s {
                self.step(s as u32, t);
            }
        }
        *next_s = max_s + 1;
        *next_t = max_t + 1;
    }

    pub fn resolve_through_degree(&self, degree : i32) {
        self.resolve_through_bidegree(degree as u32, degree);
    }

    pub fn step(&self, s : u32, t : i32) {
        // println!("step : hom_deg : {}, int_deg : {}", homological_degree, degree);
        self.inner.complex().compute_through_bidegree(s, t);
        self.inner.step_resolution(s, t);
        if t - (s as i32) < self.min_degree() {
            return;
        }
        let module = self.module(s);
        let num_gens = module.number_of_gens_in_degree(t);
        if let Some(f) = &self.add_class {
            f(s, t, num_gens);
        }
        self.compute_filtration_one_products(s, t);
        self.construct_maps_to_unit(s, t);
        self.extend_maps_to_unit(s, t);
        self.compute_products(s, t, &self.product_list);
        self.compute_self_maps(s, t);
    }

    fn compute_filtration_one_products(&self, target_s : u32, target_t : i32){
        if target_s == 0 {
            return;
        }
        let source_s = target_s - 1;

        let source = self.module(source_s);
        let target = self.module(target_s);

        let target_dim = target.number_of_gens_in_degree(target_t);

        for (op_name, op_degree, op_index) in &self.filtration_one_products {
            let source_t = target_t - *op_degree;
            if source_t - (source_s as i32) < self.min_degree(){
                continue;
            }
            let source_dim = source.number_of_gens_in_degree(source_t);

            let d = self.differential(target_s);

            let mut products = vec![Vec::with_capacity(target_dim); source_dim];

            for i in 0 .. target_dim {
                let dx = d.output(target_t, i);

                for j in 0 .. source_dim {
                    let idx = source.operation_generator_to_index(*op_degree, *op_index, source_t, j);
                    products[j].push(dx.entry(idx));
                }
            }

            self.add_structline(op_name, source_s, source_t, target_s, target_t, true, products);
        }
    }

    pub fn add_structline(
            &self,
            name : &str,
            source_s : u32, source_t : i32,
            target_s : u32, target_t : i32,
            left : bool,
            products : Vec<Vec<u32>>
    ){
        if let Some(add_structline) = &self.add_structline {
            add_structline(name, source_s, source_t, target_s, target_t, left, products);
        }
    }

    fn max_computed_degree(&self) -> i32 {
        *self.next_t.lock().unwrap() - 1
    }

    fn max_computed_homological_degree(&self) -> u32 {
        *self.next_s.lock().unwrap() - 1
    }

    pub fn graded_dimension_string(&self) -> String {
        let mut result = String::new();
        let min_degree = self.min_degree();
        let max_degree = self.max_computed_degree();
        let max_hom_deg = self.max_computed_homological_degree(); //(max_degree - min_degree) as u32 / (self.prime() + 1); //self.get_max_hom_deg();
        for i in (0 ..= max_hom_deg).rev() {
            for j in min_degree + i as i32 ..= max_degree {
                let n = self.module(i).number_of_gens_in_degree(j);
                match n {
                    0 => result.push_str("  "),
                    1 => result.push_str("· "),
                    2 => result.push_str(": "),
                    3 => result.push_str("∴ "),
                    4 => result.push_str("⁘ "),
                    5 => result.push_str("⁙ "),
                    _ => result.push_str(&format!("{} ", n))
                }
            }
            result.push_str("\n");
            // If it is empty so far, don't print anything
            if result.trim_start().is_empty() {
                result = String::new();
            }
        }
        return result;
    }
}

// Product algorithms
impl<CC> Resolution<CC> where
    CC : ChainComplex
{
    /// This function computes the products between the element most recently added to product_list
    /// and the parts of Ext that have already been computed. This function should be called right
    /// after `add_product`, unless `resolve_through_degree`/`resolve_through_bidegree` has never been
    /// called.
    ///
    /// This is made separate from `add_product` because extend_maps_to_unit needs a borrow of
    /// `self`, but `add_product` takes in a mutable borrow.
    pub fn catch_up_products(&self) {
        let new_product = [self.product_list.last().unwrap().clone()];
        let next_s = *self.next_s.lock().unwrap();
        if next_s > 0 {
            let min_degree = self.min_degree();
            let max_s = next_s - 1;
            let max_t = *self.next_t.lock().unwrap() - 1;

            self.construct_maps_to_unit(max_s, max_t);

            #[cfg(feature = "concurrent")]
            self.extend_maps_to_unit_concurrent(max_s, max_t);

            #[cfg(not(feature = "concurrent"))]
            self.extend_maps_to_unit(max_s, max_t);

            for t in min_degree ..= max_t {
                for s in 0 ..= max_s {
                    self.compute_products(s, t, &new_product);
                }
            }
        }
    }

    /// This ensures the chain_maps_to_unit_resolution are defined such that we can compute products up
    /// to bidegree (s, t)
    #[cfg(feature = "concurrent")]
    fn extend_maps_to_unit_concurrent(&self, s : u32, t : i32) {
        let max_hom_deg = min(s, self.max_product_homological_degree);
        let min_degree = self.min_degree();
        for i in 0 ..= s {
            let module = self.module(i);
            let max_s = min(s, i + self.max_product_homological_degree);
            let maps = &self.chain_maps_to_unit_resolution[i as usize];

            (min_degree ..= t).into_par_iter().for_each(|j| {
                let num_gens = module.number_of_gens_in_degree(j);
                for k in 0 .. num_gens {
                        maps[j][k].extend(max_s, t)
                }
            });
        }
    }
}

impl<CC : ChainComplex> Resolution<CC> {
    /// The return value is whether the product was actually added. If the product is already
    /// present, we do nothing.
    pub fn add_product(&mut self, s : u32, t : i32, class : Vec<u32>, name : &str) -> bool {
        let name = name.to_string();
        if !self.product_names.contains(&name) {
            self.product_names.insert(name.clone());
            self.construct_unit_resolution();
            if s > self.max_product_homological_degree {
                self.max_product_homological_degree = s;
            }

            // We must add a product into product_list before calling compute_products, since
            // compute_products aborts when product_list is empty.
            self.product_list.push(Cocycle { s, t, class, name });
            true
        } else {
            false
        }
    }

    pub fn construct_unit_resolution(&mut self) {
        if self.unit_resolution.is_none() {
            let unit_module = Arc::new(FiniteModule::from(FDModule::new(self.algebra(), String::from("unit"), BiVec::from_vec(0, vec![1]))));
            let ccdz = Arc::new(FiniteChainComplex::ccdz(unit_module));
            let unit_resolution = Arc::new(RwLock::new(Resolution::new(ccdz, None, None)));
            self.unit_resolution = Some(Arc::downgrade(&unit_resolution));
            self.unit_resolution_owner = Some(unit_resolution);
        }
    }

    pub fn set_unit_resolution(&mut self, unit_res : Weak<RwLock<Resolution<CCC>>>) {
        if self.chain_maps_to_unit_resolution.len() > 0 {
            panic!("Cannot change unit resolution after you start computing products");
        }
        self.unit_resolution = Some(unit_res);
    }

    /// Compute products whose result lie in degrees up to (s, t)
    fn compute_products(&self, s : u32, t : i32, products: &[Cocycle]) {
        for elt in products {
            self.compute_product_step(elt, s, t);
        }
    }

    /// Target = result of the product
    /// Source = multiplicand
    fn compute_product_step(&self, elt : &Cocycle, target_s : u32, target_t : i32) {
        if target_s < elt.s {
            return;
        }
        let source_s = target_s - elt.s;
        let source_t = target_t - elt.t;

        if source_t - (source_s as i32) < self.min_degree() {
            return;
        }

        let source_dim = self.inner.number_of_gens_in_bidegree(source_s, source_t);
        let target_dim = self.inner.number_of_gens_in_bidegree(target_s, target_t);

        let mut products = Vec::with_capacity(source_dim);
        for k in 0 .. source_dim {
            products.push(Vec::with_capacity(target_dim));

            let f = &self.chain_maps_to_unit_resolution[source_s][source_t][k];

            let unit_res_ = self.unit_resolution.as_ref().unwrap().upgrade().unwrap();
            let unit_res = unit_res_.read().unwrap();
            let output_module = unit_res.module(elt.s);

            for l in 0 .. target_dim {
                let result = f.get_map(elt.s).output(target_t, l);
                let mut val = 0;
                for i in 0 .. elt.class.len() {
                    if elt.class[i] != 0 {
                        let idx = output_module.operation_generator_to_index(0, 0, elt.t, i);
                        val += elt.class[i] * result.entry(idx);
                    }
                }
                products[k].push(val % self.prime());
            }
        }
        self.add_structline(&elt.name, source_s, source_t, target_s, target_t, true, products);
    }

    fn construct_maps_to_unit(&self, s : u32, t : i32) {
        // If there are no products, we return
        if self.product_list.len() == 0 {
            return;
        }

        let p = self.prime();
        let s_idx = s as usize;

        // Populate the arrays if the ResolutionHomomorphisms have not been defined.
        for new_s in 0 ..= s_idx {
            if new_s == self.chain_maps_to_unit_resolution.len() {
                self.chain_maps_to_unit_resolution.push(OnceBiVec::new(self.min_degree()));
            }

            while t >= self.chain_maps_to_unit_resolution[new_s].len() {
                let new_t = self.chain_maps_to_unit_resolution[new_s].len();
                self.chain_maps_to_unit_resolution[new_s].push(OnceVec::new());

                let num_gens = self.module(new_s as u32).number_of_gens_in_degree(new_t);
                if num_gens > 0 {
                    let mut unit_vector = Matrix::new(p, num_gens, 1);
                    for j in 0 .. num_gens {
                        let f = ResolutionHomomorphism::new(
                            format!("(hom_deg : {}, int_deg : {}, idx : {})", new_s, new_t, j),
                            Arc::downgrade(&self.inner), Arc::downgrade(&self.unit_resolution.as_ref().unwrap().upgrade().unwrap().read().unwrap().inner),
                            new_s as u32, new_t
                            );
                        unit_vector[j].set_entry(0, 1);
                        f.extend_step(new_s as u32, new_t, Some(&mut unit_vector));
                        unit_vector[j].set_to_zero();
                        self.chain_maps_to_unit_resolution[new_s][new_t].push(f);
                    }
                }
            }
        }
    }

    /// This ensures the chain_maps_to_unit_resolution are defined such that we can compute products up
    /// to bidegree (s, t)
    fn extend_maps_to_unit(&self, s : u32, t : i32) {
        // If there are no products, we return
        if self.product_list.len() == 0 {
            return;
        }

        // Now we actually extend the maps.
        let min_degree = self.min_degree();
        for i in 0 ..= s {
            for j in min_degree ..= t {
                let max_s = min(s, i + self.max_product_homological_degree);
                let num_gens = self.module(i).number_of_gens_in_degree(j);
                for k in 0 .. num_gens {
                    let f = &self.chain_maps_to_unit_resolution[i as usize][j][k];
                    f.extend(max_s, t);
                }
            }
        }
    }
}

// Self map algorithms
impl<CC : ChainComplex> Resolution<CC> {
    /// The return value is whether the self map was actually added. If the self map is already
    /// present, we do nothing.
    pub fn add_self_map(&mut self, s : u32, t : i32, name : &str, map_data : Matrix) -> bool {
        let name = name.to_string();
        if !self.product_names.contains(&name) {
            self.product_names.insert(name.clone());
            self.self_maps.push(
                SelfMap {
                    s, t, name : name, map_data,
                    map : ResolutionHomomorphism::new("".to_string(), Arc::downgrade(&self.inner), Arc::downgrade(&self.inner), s, t)
                });
            true
        } else {
            false
        }
    }

    /// We compute the products by self maps where the result has degree (s, t).
    fn compute_self_maps(&self, target_s : u32, target_t : i32) {
        let p = self.prime();
        for f in &self.self_maps {
            if target_s < f.s {
                return;
            }
            let source_s = target_s - f.s;
            let source_t = target_t - f.t;

            if source_t - (source_s as i32) < self.min_degree() {
                continue;
            }
            if source_s == 0 && source_t == self.min_degree() {
                f.map.extend_step(target_s, target_t, Some(&f.map_data));
            }
            f.map.extend(target_s, target_t);

            let source = self.module(source_s);
            let target = self.module(target_s);

            let source_dim = source.number_of_gens_in_degree(source_t);
            let target_dim = target.number_of_gens_in_degree(target_t);

            let mut products = vec![Vec::with_capacity(target_dim); source_dim];

            for j in 0 .. target_dim {
                let result = f.map.get_map(source_s).output(target_t, j);

                for k in 0 .. source_dim {
                    let vector_idx = source.operation_generator_to_index(0, 0, source_t, k);
                    products[k].push(result.entry(vector_idx));
                }
            }
            self.add_structline(&f.name, source_s, source_t, target_s, target_t, false, products);
        }
    }
}

impl<CC : ChainComplex> Resolution<CC>
{
    pub fn algebra(&self) -> Arc<AlgebraAny> {
        self.inner.complex().algebra()
    }

    pub fn prime(&self) -> u32 {
        self.inner.prime()
    }

    pub fn module(&self, homological_degree : u32) -> Arc<FreeModule> {
        self.inner.module(homological_degree)
    }

    pub fn min_degree(&self) -> i32 {
        self.inner.complex().min_degree()
    }

    pub fn differential(&self, s : u32) -> Arc<FreeModuleHomomorphism<FreeModule>> {
        self.inner.differential(s)
    }
}
